### ISSUE TITLE
onehost --cluster invalid option

### ISSUE THREAD

**Issue by conxuro** [OpenNebula/one#3381] opened 2019-05-29 10:18 UTC
**Description**
onehost command option "-c, --cluster id|name" shows that is invalid, in spite of man page and --help option shows it. Also -c option is duplicated in manual and help.

**To Reproduce**
Executing `onehost list --cluster 1` and `man onehost` or `onehost --help | grep "\-c,"`.

**Expected behavior**
That command will do something or remove this option from manual and help.

**Details**
 - Affected Component: onehost
 - Hypervisor: KVM
 - Version: 5.8.0

**Additional context**
```
# onehost list --cluster 100
invalid option: --cluster
# onehost --help | grep "\-c,"
     -c, --cluster id|name     Selects the cluster
     -c, --listconf conf       Selects a predefined column list
# man onehost | grep "\-c,"
        -c, --cluster id|name     Selects the cluster
        -c, --listconf conf       Selects a predefined column lis
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment] 2019-06-04 09:12
Hello @conxuro 

The option `-c cluster` is only available in the command `onehost create`, is not available in the `list` command. To check the help of each sub command use `onehost list --help` for example. If you use `onehost --help` you will see the help for all sub commands, that's why you see the cluster there.

Closing this, because it's not a bug.

**Closed by al3xhh** 2019-06-04 09:12 UTC
Labels: Category: CLI, Community, Priority: Normal, Status: Accepted, Type: Bug
