### ISSUE TITLE
confusion with image creation and restricted directories

### ISSUE THREAD

**Issue by loveshack** [OpenNebula/one#4144] opened 2020-01-31 11:02 UTC
**Description**
My first attempt to install a new image failed, and took some time to understand. I can't be the first to trip on this, but I can't see a previous report.

I tried to upload a qcow2 image, built in oneadmin's home, with oneimage create.  That appeared to succeed, but the image went into the error state with "Not allowed to copy image file".  It wasn't obvious to me what the problem was, so I tried via sunstone to see if it gave a clue, and that succeeded with the image in the same place.

It took me some grepping around to find out why oneimage was failing.  RESTRICTED_DIRS and SAFE_DIRS are in the datastore documentation, but I didn't initially find them, and it's rather un-obvious when you use oneimage. It would help if oneimage checked the restriction and reported an error, but I can't look into implementing that now.

I assume it's a bug that sunstone succeeds.

**Expected behavior**
Error from oneimage, with a clear message about the directories, and consistency between oneimage and sunstone.

**Details**
 - Affected Component: Storage, Sunstone
 - Version: 5.10.1

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment] 2020-02-03 17:27
We've checked the behaviour, and it should be exactly the same through the CLI and Sunstone, since the error message comes from the datastore driver. We couldn't replicate the different behaviour. Could you please check and let us know the steps to reproduce this different behaviour if you manage to reproduce it?

We agree that the error message can be improved, we will make the appropriate change.

**Comment by tinova** [comment] 2020-02-03 17:28
Closing until further feedback is provided.

**Comment by sbbarragan** [comment] 2020-02-03 17:28
PRs to merge:
• one: #4152
• docs: OpenNebula/docs/pull/922

**Closed** 2020-02-03 17:28 UTC
Labels: Category: Orchestration - Flow, Category: Sunstone, Community, Status: Pending, Type: Bug

**Comment by loveshack** [comment] 2020-02-04 15:42
You wrote: 

> We've checked the behaviour, and it should be exactly the same through
> the CLI and Sunstone, since the error message comes from the datastore
> driver. We couldn't replicate the different behaviour. Could you
> please check and let us know the steps to reproduce this different
> behaviour if you manage to reproduce it?

It's reproducible.  If I'm in ~oneadmin, oneimage create
obviously fails.  If I upload from the same place via sunstone, it
works.

I should have looked at the log for the sunstone attempt previously.
What I see for the successful sunstone upload is

  [Z0][ImM][I]: Copying /var/tmp/1401290752-<image>

where <image> is the basename of the image that failed from the CLI, so
it's obviously getting staged by sunstone, which explains the
difference.  I guess this isn't a bug and isn't a big deal anyhow.

I haven't looked at it yet, but thanks for clarifying the message.
