### ISSUE TITLE
Can't skip SSL validation using pyone

### ISSUE THREAD

**Issue by palvarez89** [OpenNebula/one#5947] opened 2022-08-23 15:54 UTC
**Description**

It's currently not possible to skip SSL validation using `pyone` bindings.

Ansible opennebula modules [try to set the context here](https://github.com/ansible-collections/community.general/blob/main/plugins/module_utils/opennebula.py#L97) to bypass SSL verification, but `pyone` seems to have [hardcoded a setting to force validation here](https://github.com/OpenNebula/one/blob/master/src/oca/python/pyone/__init__.py#L323)

**To Reproduce**

Try to use the Ansible modules against a OpenNebula instance with self-signed certificates.

**Expected behavior**

API works

**Details**
...

**Additional context**
...

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by palvarez89** [comment] 2022-08-23 15:59
I can try to implement this if people agree it's useful.

**Comment by kvakanet** [comment] 2022-08-28 16:30
Hello! 

Bad example in documentation (ssl verify not disabled and url http)
```
import pyone
import ssl
one = pyone.OneServer("http://one:2633/RPC2", session="oneadmin:onepass", context=ssl._create_unverified_context() 
```

**Comment by xorel** [comment] 2022-08-29 15:18
I think the issue is fixed in the master by this patch
https://github.com/OpenNebula/one/commit/c1f5c649f2995e792cb0116852964bdb6e6c34a1

The docs should be updated with the new release in the upcoming weeks
https://github.com/OpenNebula/docs/pull/2382/files

Could you verify?

**Comment by palvarez89** [comment] 2022-08-30 16:23
Amazing @xorel, this seems to work well, thank you!

**Closed** 2022-09-02 10:13 UTC
