### ISSUE TITLE
[one.vm.migrate] Migrate action is not available for state RUNNING

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3995] opened 2019-11-27 10:17 UTC
**Description**
Just faced with this weird issue
```
[one.vm.migrate] Migrate action is not available for state RUNNING
```
That's weird because my VM is having
```
  <STATE>3</STATE>
  <LCM_STATE>3</LCM_STATE>
  <PREV_STATE>3</PREV_STATE>
  <PREV_LCM_STATE>3</PREV_LCM_STATE>
```
**To Reproduce**
Didn't found steps yet

**Expected behavior**
Start the migtation

**Details**
 - Affected Component: oned
 - Hypervisor: KVM
 - Version: 5.8.5

**Additional context**
https://github.com/OpenNebula/one/blob/23a698d6e97f75cba4985c7121686534c5791cc6/src/rm/RequestManagerVirtualMachine.cc#L1162-L1175

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment] 2020-02-25 12:34
Weird indeed, couldn't reproduce.

* Is this happening in 5.10.x as well?
* Any luck making this reproducible?

Closing until this becomes reproducible.

**Closed by tinova** 2020-02-25 12:34 UTC
