### ISSUE TITLE
windows VM firstly not created if disk size is changed

### ISSUE THREAD

**Issue by darkfritz2** [OpenNebula/one#5377] opened 2021-04-30 16:01 UTC
**Description**
We made a windows VM template. If you don't change anything than the VM instantiates and everything is working fine.
If i change the disk size and click on create button, then i get the error:

[one.template.instantiate] Error allocating a new virtual machine template. Wrong OS/BOOT value. Device with DISK_ID 1 not found

but if i click on create again (no change at all - the disk size still changed) than everything works.

**To Reproduce**
1. Create Windows VM without any changes - click on "Create" button - success!
2. Create Windows VM with disk size changed - click on "Create" button first time - fail!
3. Click on "Create" button second time - success!

**Expected behavior**
Expected that after change of the disk size and click the first time on "Create" button - it creates the VM without errors.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 6.0.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment] 2021-12-16 15:46
We will close this issue because we can't reproduce it in version 6.2.
If you can reproduce it in that version, feel free to reopen it.

**Closed by FrederickBor** 2021-12-16 15:46 UTC
Labels: Status: Pending, Community, Category: Sunstone, Type: Bug, Priority: Normal
