### ISSUE TITLE
ONE does not take care about pending operations after HA Raft leader change

### ISSUE THREAD

**Issue by hydro-b** [OpenNebula/one#2038] opened 2018-04-26 12:37 UTC
- [X] 5.4.10
- [X] 5.4.11

## Component
- [ ] Federation and HA

## Description
Actions (IMAGE create, VM (live) migrate) done (just) before ONE HA leader changes from the node where the action was inititated will never complete on the new leader. Leading to "LOCKED" images (that might or might not have been actually created, VMs in MIGRATE state (that might have, or might not have been migrated)

### Expected Behavior
Leader change is completely transparant and takes care of pending operations.

### Actual Behavior
"State" seems to be lost when ONE changes leader regarding pending operations. 

## How to reproduce
Perform regular operations, leader change needs to happen (force leader change by stopping opennebula on the current leader), pending action will never complete

**Comment by tinova** [comment] 2019-05-27 10:55
By design, operations made while HA leader adjustment needs to be performed manually

**Comment by hydro-b** [comment] 2019-06-24 07:38
> By design, operations made while HA leader adjustment needs to be performed manually

Does this also include the handling of "HOST_HOOKS" on "failure". See issue [https://github.com/OpenNebula/one/issues/3021](url).

The whole idea of RAFT HA / HOST_HOOKS is to achieve high(er) availability. If this potentially can lead to situations where HOST_HOOKS are not triggered, or erroneously triggered multiple times, it will lead to more issues than it tries to solve.

**Comment by tinova** [comment] 2019-06-24 16:22
Hook callbacks cannot be distributed in the current design. Without HA those are lost as well.

With the new hook subsystem being worked on for 5.10 (#3380), there will be a list of failed hooks that can be retried, simplifying this management.

**Comment by rsmontero** [comment] 2021-09-06 16:54
Closing this, hooks (and specific hook executions) can be queried and retried. There is an extra step needed to check this information. There are still situations were hook callbacks/triggering maybe lost; requiring manual intervention on some situations.

**Closed by rsmontero** 2021-09-06 16:54 UTC
Labels: Status: Pending, Community, Category: Core & System, Type: Bug
