### ISSUE TITLE
OneFlow LXD Service Issues after 5.12 Upgrade 

### ISSUE THREAD

**Issue by ilhaan** [OpenNebula/one#5308] opened 2021-03-22 20:40 UTC
**Description**
ONE services that use LXD containers are reporting `WARNING` state. Attempts to recover these services results in `Service cannot be recovered in state: WARNING` error messages. Being in this state, services are unable to perform scaling actions. 

This issue seems to have started after upgrading to ONE 5.12. Initially, we had an issue where ONE was unable to monitor LXD guests. That was resolved following instructions [here](https://github.com/OpenNebula/one/issues/5295). 

**To Reproduce**
* Upgrade OpenNebula from 5.10.1 to 5.12.0.3 following instructions [here](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/start_here.html#start-here).
* Update LXD hypervisors following instructions from [here](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/upgrading_single.html#step-11-update-the-hypervisors-lxd-kvm-only).
* Apply patches mentioned [here](https://github.com/OpenNebula/one/issues/5295#issuecomment-796851512)

**Expected behavior**
Services in `RUNNING` state and able to scale up and down. 

**Details**
 - Affected Component: LXD Services 
 - Hypervisor: LXD
 - Version: 5.12.0.3 (with above mentioned LXD patches applied) 

**Additional context**
We currently have a few services reporting `WARNING` state. 

One service does not have any active guests at the moment and attempts to recover the service results in `Service cannot be recovered in state: WARNING`. Inspecting `/var/log/one/oneflow.log` shows the following errors:

```
Mon Mar 15 14:29:52 2021 [I]: [WD] Warning 154: jj_deploy is DONE
Mon Mar 15 14:29:52 2021 [I]: [WD] Update 154:jj_deploy cardinality to -1
Mon Mar 15 14:30:02 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:02 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0335
Mon Mar 15 14:30:02 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:02 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0110
Mon Mar 15 14:30:02 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:02 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0148
Mon Mar 15 14:30:07 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:07 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0079
Mon Mar 15 14:30:10 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:10 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0080
Mon Mar 15 14:30:11 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:11 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0078
Mon Mar 15 14:30:11 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:11 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0079
Mon Mar 15 14:30:11 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:11 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0083
Mon Mar 15 14:30:12 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:12 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0081
Mon Mar 15 14:30:22 2021 [I]: [WD] Warning 154: jj_deploy is DONE
Mon Mar 15 14:30:23 2021 [I]: [WD] Update 154:jj_deploy cardinality to -1
```

A second service that is in `WARNING` state has LXD guests that are all in `RUNNING` state. However, `/var/log/one/oned.log` shows the following for all guests under this service:

```
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:6736 UID:0 IP:127.0.0.1 one.vm.action invoked , "resume", 33309
Mon Mar 15 14:34:31 2021 [Z0][DiM][D]: Resuming VM 33309
Mon Mar 15 14:34:31 2021 [Z0][DiM][E]: Could not resume VM 33309, wrong state RUNNING.
Mon Mar 15 14:34:31 2021 [Z0][ReM][E]: Req:6736 UID:6 one.vm.action result FAILURE [one.vm.action] Error performing action "resume": This action is not available for state RUNNING
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:1936 UID:0 IP:127.0.0.1 one.vm.update invoked , 33309, "<TEMPLATE><HYPERVISO...", 1
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:1936 UID:0 one.vm.update result SUCCESS, 33309
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:1760 UID:0 IP:127.0.0.1 one.vmpool.infoextended invoked , -2, -1, -1, -1
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:1760 UID:0 one.vmpool.infoextended result SUCCESS, "<VM_POOL><VM><ID>340..."
```

Above pattern is repeated for all guests in the service.

Unsure how to debug further. 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment] 2021-05-12 09:41
Hello @ilhaan,

First of all, thank you very much for reporting the bug.

As you noticed, the service can not be recovered in **WARNING** state, as this is an special state that indicates that something is wrong in the service itself.

In order to try to reproduce the issue I need to know the following information:

- What specific steps were performed in each service, the one which has no VM and the one with all the VMs in running.
- It would be great to have both services log, it is located in `/var/log/one/oneflow/<service_id>.log`.
- It would be great to know if the problem happens with KVM too.

Best,
Álex.

**Comment by al3xhh** [comment] 2021-11-04 08:58
Can't reproduce it, closing until further information is provided.

**Closed by al3xhh** 2021-11-04 08:58 UTC
Labels: Status: Pending, Community, Category: Orchestration - Flow, Priority: Low
