### ISSUE TITLE
Show VM running hours in showback

### ISSUE THREAD

**Issue by fm4991** [OpenNebula/one#5610] opened 2021-11-10 17:02 UTC
### Request #28394

**Description**
Since it is possible to configure oneshowback to calculate only the running hours of a VM it would be great to have the running hours also shown in the CLI and sunstone.
https://docs.opennebula.io/6.2/installation_and_configuration/opennebula_services/oned.html#oned-conf-default-showback
`SHOWBACK_ONLY_RUNNING = "yes"`
**Use case**
Since we bill our customers based on the running hours of their VMs, they would like to see the running hours somewhere.

**Interface Changes**
Add an additional column in Sunstone showback and on the cli which displays the running hours of each VM.

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment] 2021-11-15 20:51
Duplicate of #5561

**Closed by paczerny** 2021-11-15 20:51 UTC
