### ISSUE TITLE
resched not working when NIC NETWORK_MODE / SCHED_REQUIREMENTS defined

### ISSUE THREAD

**Issue by mzealey** [OpenNebula/one#5180] opened 2020-11-17 20:34 UTC
**Description**

If I attach a NIC to a VM with:

```
NIC = [
  AR_ID = "0",
  BRIDGE = "br.dummy",
  BRIDGE_TYPE = "linux",
  CLUSTER_ID = "0,100,101",
  IP = "10.99.0.9",
  NAME = "NIC0",
  NETWORK = "dummy bridge 2",
  NETWORK_ID = "18",
  NIC_ID = "0",
  SECURITY_GROUPS = "0",
  TARGET = "one-131-0",
  VN_MAD = "bridge" ]
```

and then resched the VM, it migrates to another host without issue.

If I add:

```
  NETWORK_MODE = "auto",
  SCHED_REQUIREMENTS = "NETWORK_TYPE=\"dummy\"",
```

to it it refuses to reschedule

**Expected behavior**

I would have expected that the SCHED_REQUIREMENTS/NETWORK_MODE were only looked at on the initial deployment, and that the allocated IP/MAC address would remain the same when rescheduled. I would not expect resched to be bombing out.

**Details**
 - Affected Component: Scheduler
 - Hypervisor: KVM
 - Version: 5.12.0.3

**Additional context**

sched debug logs when it works:

```
Tue Nov 17 20:28:29 2020 [Z0][VM][D]: Pending/rescheduling VM and capacity requirements:
  ACTION       VM  CPU      Memory PCI   System DS  Image DS
------------------------------------------------------------
 RESCHED      131   20     1048576   0       10240  DS 100: 0 

Tue Nov 17 20:28:29 2020 [Z0][HOST][D]: Discovered Hosts (enabled):
ID          : 2
CLUSTER_ID  : 100
PUBLIC      : 0
MEM_USAGE   : 33554432
CPU_USAGE   : 400
MAX_MEM     : 263716864
MAX_CPU     : 4800
FREE_DISK   : 4639300
RUNNING_VMS : 2

 DSID         FREE_MB 
------------------------------
  103         4639300 

    PCI ADDRESS    CLASS   VENDOR   DEVICE     VMID 
-------------------------------------------------------

---------------------------------------------------------------------------
Node: 0 Memory: 0/125G
---------------------------------------------------------------------------
( 0 24)( 1 25)( 2 26)( 3 27)( 4 28)( 5 29)( 6 30)( 7 31)( 8 32)( 9 33)(10 34)(11 35)
( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)
---------------------------------------------------------------------------
Node: 1 Memory: 0/125G
---------------------------------------------------------------------------
(12 36)(13 37)(14 38)(15 39)(16 40)(17 41)(18 42)(19 43)(20 44)(21 45)(22 46)(23 47)
( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)
---------------------------------------------------------------------------

ID          : 4
CLUSTER_ID  : 100
PUBLIC      : 0
MEM_USAGE   : 172425216
CPU_USAGE   : 1980
MAX_MEM     : 481086668
MAX_CPU     : 9451
FREE_DISK   : 26583069
RUNNING_VMS : 18

 DSID         FREE_MB 
------------------------------
  103        26583069 

    PCI ADDRESS    CLASS   VENDOR   DEVICE     VMID 
-------------------------------------------------------

---------------------------------------------------------------------------
Node: 0 Memory: 0/125G
---------------------------------------------------------------------------
( 0 24)( 1 25)( 2 26)( 3 27)( 4 28)( 5 29)( 6 30)( 7 31)( 8 32)( 9 33)(10 34)(11 35)
( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)
---------------------------------------------------------------------------
Node: 1 Memory: 0/125G
---------------------------------------------------------------------------
(12 36)(13 37)(14 38)(15 39)(16 40)(17 41)(18 42)(19 43)(20 44)(21 45)(22 46)(23 47)
( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)( -  -)
---------------------------------------------------------------------------


Tue Nov 17 20:28:29 2020 [Z0][VM][D]: VMs in VMGroups:

Tue Nov 17 20:28:29 2020 [Z0][VNET][D]: Discovered VNETS:
      ID   Leases 
--------------------
       0       20 
       2       23 
       3        0 
       4        0 
       5        0 
       6        0 
       7        0 
       8        0 
       9        0 
      10        0 
      11        0 
      12        0 
      13        0 
      14        0 
      15        0 
      16      254 
      18      243 

Tue Nov 17 20:28:29 2020 [Z0][SCHED][D]: Getting VM and Host information. Total time: 0.06s
Tue Nov 17 20:28:29 2020 [Z0][VMGRP][D]: VM Group Scheduling information
********************************************************************************
SCHEDULING RESULTS FOR VM GROUP 0, test
********************************************************************************
ROLE ID NAME     POLICY       VMS
--------------------------------------------------------------------------------
0       test     ANTI_AFFINED 

RULES
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
Intra-role affinity requirements
VMID     REQUIREMENTS
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Inter-role affinity requirements
VMID     REQUIREMENTS
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Intra-role Anti-affinity rules 
ROLE     VM       ANTI_AFFINITY REQUIRMENTS
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Inter-role Anti-affinity rules 
ROLE     VM       ANTI_AFFINITY REQUIRMENTS
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Host affinity rules 
ROLE     VM       AFFINITY REQUIRMENTS
--------------------------------------------------------------------------------

Tue Nov 17 20:28:29 2020 [Z0][SCHED][D]: Setting VM groups placement constraints. Total time: 0.00s
Tue Nov 17 20:28:29 2020 [Z0][ACL][D]: Request #2 HOST/#2 MANAGE #0
Tue Nov 17 20:28:29 2020 [Z0][ACL][D]: > Rule  * HOST/#2  #0
Tue Nov 17 20:28:29 2020 [Z0][ACL][D]: > Rule  * HOST/* MANAGE *
Tue Nov 17 20:28:29 2020 [Z0][ACL][D]: Permission granted
Tue Nov 17 20:28:29 2020 [Z0][SCHED][D]: Host 4 discarded for VM 131. VM cannot be migrated to its current Host.
Tue Nov 17 20:28:29 2020 [Z0][RANK][D]: Rank evaluation for expression : - ( (USED_CPU / MAX_CPU + MEM_USAGE / MAX_MEM) * 1000 + ("DATASTORES/USED_DISK" / "DATASTORES/MAX_DISK") * 1000 )
Tue Nov 17 20:28:29 2020 [Z0][RANK][D]: ID: 2 Rank: -445
Tue Nov 17 20:28:29 2020 [Z0][SCHED][D]: Match Making statistics:
        Number of VMs:             1
        Total time:                0s
        Total Cluster Match time:  0s
        Total Host Match time:     0.00s
        Total Host Ranking time:   0.00s
        Total DS Match time:       0s
        Total DS Ranking time:     0s
        Total Network Match time:  0s
        Total Network Ranking time:0s

Tue Nov 17 20:28:29 2020 [Z0][SCHED][D]: Scheduling Results:
Virtual Machine: 131

        PRI     ID - HOSTS
        ------------------------
        -1      2

        PRI     ID - DATASTORES
        ------------------------
        0       103


Tue Nov 17 20:28:29 2020 [Z0][SCHED][D]: Dispatching VMs to hosts:
        VMID    Priority        Host    System DS
        --------------------------------------------------------------
        131     0               2       103
```

when it fails to resched it is identical except that the last line indicating that the VM rescheduled is not there. It then repeats every time the scheduler runs.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by paczerny** [comment] 2020-12-14 19:39
The problem wasn't the `SCHED_REQUIREMENTS` but the `NETWORK_MODE = "auto"`
Duplicate of #5052

**Closed by paczerny** 2020-12-14 19:39 UTC
