### ISSUE TITLE
LXD Monitoring Errors After Upgrade to 5.12

### ISSUE THREAD

**Issue by ilhaan** [OpenNebula/one#5295] opened 2021-03-11 00:48 UTC
**Description**

Upgraded OpenNebula from 5.10.1 to 5.12.0.3 following instructions [here](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/start_here.html#start-here). Post upgrade, LXD guests in OpenNebula are reporting `UNKNOWN` status. This is preventing shutdown and restart of LXD guests. 

Inspection of `oned.log` on front-end node shows the following errors: 

```
Wed Mar 10 16:34:29 2021 [Z0][InM][E]: Error parsing VM_STATE: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 0, columns 8:11
Wed Mar 10 16:34:29 2021 [Z0][InM][E]: Received message was: String can't be coerced into Integer
```

```
Wed Mar 10 16:35:07 2021 [Z0][InM][E]: Error parsing VM_STATE: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 32563, columns 8:11
Wed Mar 10 16:35:07 2021 [Z0][InM][E]: Received message was: String can't be coerced into Integer
```

```
Wed Mar 10 16:35:07 2021 [Z0][InM][E]: Error parsing VM_STATE: syntax error, unexpected VARIABLE, expecting EQUAL or EQUAL_EMPTY at line 22006, columns 8:11
Wed Mar 10 16:35:07 2021 [Z0][InM][E]: Received message was: String can't be coerced into Integer
```

**To Reproduce**
* Upgrade OpenNebula from 5.10.1 to 5.12.0.3 following instructions [here](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/start_here.html#start-here).
* Update LXD hypervisors following instructions from [here](http://docs.opennebula.io/5.12/intro_release_notes/upgrades/upgrading_single.html#step-11-update-the-hypervisors-lxd-kvm-only). 

**Expected behavior**
LXD Guests monitored and not reporting `UNKNOWN` status. 

**Details**
 - Affected Component: LXD Guests 
 - Hypervisor: LXD
 - Version: 5.12.0.3

**Additional context**
I have verified the following based on past experience with OpenNebula: 
* `oneadmin` user on front-end node is able to ssh onto LXD hypervisors without any issues. 
* `oneadmin` user is able to run `lxc ...` commands on LXD hypervisors. 

Other info: 
* Using snap installed LXD: 
```
oneadmin@lxd-hypevisor-1:~$ snap list 
Name  Version  Rev    Tracking       Publisher   Notes
core  16-2.49  10859  latest/stable  canonical✓  core
lxd   3.0.4    11348  3.0/stable     canonical✓  -
```
* LXD Hypervisors running Ubuntu 18.04
* Front-end running CentOS 7 
* List of opennebula packages installed on LXD Hypervisor: 
```
oneadmin@lxd-hypervisor-1:~$ dpkg -l | grep opennebula 
ii  opennebula-common                      5.12.0.3-1.ce                                   all          Common OpenNebula package shared by various components (Community Edition)
ii  opennebula-common-onescape             5.12.0.3-1.ce                                   all          Helpers for OpenNebula OneScape project (Community Edition)
ii  opennebula-lxd-snap                    5.12.0.3-1.ce                                   amd64        LXD installed as a snap
ii  opennebula-node                        5.12.0.3-1.ce                                   all          Services for OpenNebula KVM node (Community Edition)
ii  opennebula-node-lxd                    5.12.0.3-1.ce                                   amd64        Services for OpenNebula LXD node (Community Edition)
```
* This issue was not observed prior to OpenNebula upgrade. 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment] 2021-03-11 16:11
Hello, try to apply the changes [here](https://github.com/OpenNebula/one/commit/509798676273c0aa1d4bc202cd24c4be94dd1023#diff-45d90aadddd2d062bc69c2036fa1482099d70858d6a72d003573f11c343e147d) and [here](https://github.com/OpenNebula/one/commit/7dd74b63d67f4f989d995a4c58af961b7eb4683d#diff-45d90aadddd2d062bc69c2036fa1482099d70858d6a72d003573f11c343e147d) and check if this is still happening.

**Comment by ilhaan** [comment] 2021-03-11 20:50
Hi @dann1 - applied these changes and this fixed the issue. Thanks!

For anyone else facing this issue and trying to solve this, here is what I did: 
1. Applied changes @dann1 linked above. File locations on my front-end node: 
   * `/var/lib/one/remotes/im/lxd-probes.d/vm/status/state.rb`
   * `/var/lib/one/remotes/im/lib/probe_db.rb`
2. Then ran the following as `oneadmin` user: 
```
onehost sync --force
```

LXD guests are now reporting correct status and no longer seeing errors in `oned.log`.

**Comment by dann1** [comment] 2021-03-12 15:26
@ilhaan these commits will be merged into CE some time after next release.

**Comment by ilhaan** [comment] 2021-03-12 23:31
@dann1 sounds good. Thanks for the update!

**Comment by ilhaan** [comment] 2021-03-15 21:37
@dann1 Seeing another issue that may be tied to this. A couple ONE services that use LXD guests are reporting `WARNING` state. 

One service does not have any active guests at the moment and attempts to recover the service results in `Service cannot be recovered in state: WARNING`. Inspecting `/var/log/one/oneflow.log` shows the following errors: 
```
Mon Mar 15 14:29:52 2021 [I]: [WD] Warning 154: jj_deploy is DONE
Mon Mar 15 14:29:52 2021 [I]: [WD] Update 154:jj_deploy cardinality to -1
Mon Mar 15 14:30:02 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:02 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0335
Mon Mar 15 14:30:02 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:02 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0110
Mon Mar 15 14:30:02 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:02 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0148
Mon Mar 15 14:30:07 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:07 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0079
Mon Mar 15 14:30:10 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:10 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0080
Mon Mar 15 14:30:11 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:11 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0078
Mon Mar 15 14:30:11 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:11 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0079
Mon Mar 15 14:30:11 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:11 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0083
Mon Mar 15 14:30:12 2021 [I]: 127.0.0.1 - - [15/Mar/2021:14:30:12 -0700] "GET /service/154 HTTP/1.1" 200 19058 0.0081
Mon Mar 15 14:30:22 2021 [I]: [WD] Warning 154: jj_deploy is DONE
Mon Mar 15 14:30:23 2021 [I]: [WD] Update 154:jj_deploy cardinality to -1
```

A second service that is in `WARNING` state has LXD guests that are all in `RUNNING` state. However, `/var/log/one/oned.log` shows the following for all guests under this service: 
```
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:6736 UID:0 IP:127.0.0.1 one.vm.action invoked , "resume", 33309
Mon Mar 15 14:34:31 2021 [Z0][DiM][D]: Resuming VM 33309
Mon Mar 15 14:34:31 2021 [Z0][DiM][E]: Could not resume VM 33309, wrong state RUNNING.
Mon Mar 15 14:34:31 2021 [Z0][ReM][E]: Req:6736 UID:6 one.vm.action result FAILURE [one.vm.action] Error performing action "resume": This action is not available for state RUNNING
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:1936 UID:0 IP:127.0.0.1 one.vm.update invoked , 33309, "<TEMPLATE><HYPERVISO...", 1
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:1936 UID:0 one.vm.update result SUCCESS, 33309
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:1760 UID:0 IP:127.0.0.1 one.vmpool.infoextended invoked , -2, -1, -1, -1
Mon Mar 15 14:34:31 2021 [Z0][ReM][D]: Req:1760 UID:0 one.vmpool.infoextended result SUCCESS, "<VM_POOL><VM><ID>340..."
```

Above pattern is repeated for all guests in the service. 

Any ideas on how I can fix this or debug further?

**Comment by christian7007** [comment] 2021-11-04 19:27
OneFlow have been improved in several ways since them. Please if you're able to reproduce it in latest versions reopen the issue.

**Closed by christian7007** 2021-11-04 19:27 UTC
Labels: Community, Type: Bug, Status: Accepted, Category: LXD/LXC
