### ISSUE TITLE
one commands --filter option does not work with --xml

### ISSUE THREAD

**Issue by conxuro** [OpenNebula/one#3382] opened 2019-05-29 10:28 UTC
**Description**
one* (onehost, oneuser, etc.) commands --filter option does not work with --xml option (possible with all cli one commands) but, for example, filter works well with --csv option.

**To Reproduce**
`onehost list --filter CLUSTER='<cluster_name>' --xml`
or
`onevnet list --filter GROUP=<group_name>' --xml`

**Expected behavior**
That shows only the XML from elements matching the filter. Or specify in help that --xml does not work with --filter option.

**Details**
 - Affected Component: CLI commands (one*)
 - Hypervisor: KVM
 - Version: 5.8.0

**Additional context**
Example with onehost list:
```
# onehost list --filter CLUSTER='<cluster_name>' | awk '{print $1}'
ID
4
3
2
1
0

# onehost list --filter CLUSTER='<cluster_name>' --csv | awk -F',' '{print $1}'
ID
4
3
2
1
0

# onehost list --filter CLUSTER='<cluster_name>' --xml | grep -A1 "<HOST>" | grep ID
    <ID>17</ID>
    <ID>16</ID>
    <ID>15</ID>
    <ID>14</ID>
    <ID>13</ID>
    <ID>12</ID>
    <ID>11</ID>
    <ID>10</ID>
    <ID>9</ID>
    <ID>8</ID>
    <ID>7</ID>
    <ID>6</ID>
    <ID>5</ID>
    <ID>4</ID>
    <ID>3</ID>
    <ID>2</ID>
    <ID>1</ID>
    <ID>0</ID>
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by conxuro** [comment] 2019-05-29 14:03
Title edited; the same issue found also with onedatastore, onegroup, oneimage, oneuser, onevm, onevnet and others.

**Comment by al3xhh** [comment] 2019-06-04 09:17
Hello @conxuro 

The option `--filter` does not work with `--xml`  because the **xml** output shows the full xml of the object, so you can't filter. If you want to filter using xml output you can use `grep` command. Or you can use the output without xml.

Closing this because it's not a bug.

**Closed by al3xhh** 2019-06-04 09:17 UTC
Labels: Category: CLI, Community, Priority: Normal, Status: Accepted, Type: Bug
