### ISSUE TITLE
Using :group: in /etc/one/auth/ldap_auth.conf fails if the user's CN contains brackets ( )

### ISSUE THREAD

**Issue by adriant1978** [OpenNebula/one#5309] opened 2021-03-23 18:11 UTC
**Description**
Using **:group:** in **/etc/one/auth/ldap_auth.conf** fails if the user's CN contains brackets ( )

**To Reproduce**
Configure **:group:** in **/etc/one/auth/ldap_auth.conf** to require membership of some group. Make a user with brackets in their CN a member of that group and try to log in. Error message in **/var/log/one/oned.log** is:

`Message received: LOG I 301 Exception raised with LDAP server 1: Invalid filter syntax`

**Expected behavior**
The user should be able to authenticate successfully.

**Details**
 - Affected Component: LDAP driver
 - Version: 5.12.0.3-1.ce

**Additional context**
I assume this is because brackets are special characters in LDAP and need to be escaped when the search filter is constructed, e.g.

`(member=CN=User With \(Brackets\),OU=Users,DC=my,DC=domain,DC=local)`

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment] 2022-06-27 12:11
closing as couldn't reproduce with the following:

```
[root@alma8-vcenter70-6-4-8wFLq-0 ~]# ldapsearch -x -LLL uid=* uid
dn: uid=demo_user,ou=people,dc=orga
uid: demo_user

dn: uid=userX,ou=people,dc=orga
uid: userX

dn: uid=userY,ou=people,dc=orga
uid: userY

dn: uid=user_nocloud,ou=people,dc=orga
uid: user_nocloud

dn: uid=userXY,ou=people,dc=orga
uid: userXY

dn: uid=userA1@orgA,ou=people,dc=orga
uid: userA1@orgA

dn: uid=userA2@orgA,ou=people,dc=orga
uid: userA2@orgA

dn: uid=userA3@orgA,ou=people,dc=orga
uid: userA3@orgA

dn: uid=userZ,ou=people,dc=orga
uid: userZ

dn: uid=user[test],ou=people,dc=orga
uid: user[test]

dn: uid=user(test),ou=people,dc=orga
uid: user(test)
```

**Closed by tinova** 2022-06-27 12:11 UTC
Labels: Status: Pending, Community, Type: Bug, Category: Drivers - Auth, Priority: Low
