### ISSUE TITLE
Onehem may stuck

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#4357] opened 2020-03-12 22:13 UTC
**Description**
Hi, I running onehem as external service.
oned is running in three instances with RAFT enabled.

When leader is changed virtual IP might be moved to another server or even be unreachable during leader election.

Afterwards hem is doing nothing and just stuck

**To Reproduce**
* Run oned in RAFT
* Run hem as external service with endpoint to single virtual IP address
* Change the leader

**Expected behavior**
When connection is lost hem will try to reconnect or even die, but do not stuck forever,

**Details**
 - Affected Component: Hem
 - Hypervisor: KVM
 - Version: 5.10.3

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by christian7007** [comment] 2020-04-23 13:52
Hello @kvaps,

I've been trying to reproduce the issue and it seems to work for me. Is this something that's happens to you always or just sporadically?

Let me provide some info on the test I've done, as maybe I'm losing something.

I have three frontend nodes with OpenNebula 5.10.1 installed, the HA cluster looks like this:

```
[root@localhost ~]# onezone show 0
ZONE 0 INFORMATION                                                              
ID                : 0                   
NAME              : OpenNebula          


ZONE SERVERS                                                                    
ID NAME            ENDPOINT                                                       
 0 server-0        http://10.10.0.86:2633/RPC2
 1 server-1        http://10.10.0.87:2633/RPC2
 2 server-2        http://10.10.0.88:2633/RPC2

HA & FEDERATION SYNC STATUS                                                     
ID NAME            STATE      TERM       INDEX      COMMIT     VOTE  FED_INDEX 
 0 server-0        leader     8          117        117        0     -1
 1 server-1        error      -          -          -          -     -
 2 server-2        follower   8          117        117        0     -1
```
Only `opennebula.service` is running in this nodes.

Also I have another node with `opennebula-hem.service` running inside. I've perform the following configuration changes:

**Comment by christian7007** [comment] 2020-04-23 14:02
Hello @kvaps,

I've been trying to reproduce the issue and it seems to work for me. Is this something that's happens to you always or just sporadically?

Let me provide some info on the test I've done, as maybe I'm losing something.

I have three frontend nodes with OpenNebula 5.10.1 installed, the HA cluster looks like this:

```
[root@localhost ~]# onezone show 0
ZONE 0 INFORMATION                                                              
ID                : 0                   
NAME              : OpenNebula          


ZONE SERVERS                                                                    
ID NAME            ENDPOINT                                                       
 0 server-0        http://10.10.0.86:2633/RPC2
 1 server-1        http://10.10.0.87:2633/RPC2
 2 server-2        http://10.10.0.88:2633/RPC2

HA & FEDERATION SYNC STATUS                                                     
ID NAME            STATE      TERM       INDEX      COMMIT     VOTE  FED_INDEX 
 0 server-0        leader     8          128        128        0     -1
 1 server-1        follower   8          128        128        -1    -1
 2 server-2        follower   8          128        128        0     -1
```



Only `opennebula.service` is running in those nodes.

Also I have another node with `opennebula-hem.service` running inside. I've perform the following configuration changes:
   - `:subscriber_endpoint` and `:replier_endpoint` onehem-server.conf attributes point to the VIP.
   - I've defined `one_auth` and `one_endpoint` at `/var/lib/one/.one`:
      ```
      grep -R . /var/lib/one/.one/
      /var/lib/one/.one/one_endpoint:http://<vip>:2633/RPC2
      /var/lib/one/.one/one_auth:<user>:<password>
      ``` 
It seems that hooks are correctly executed except for those executed during election period, which makes sense as during this period the VIP is not configured in any of the hosts.

**Comment by kvaps** [comment] 2020-04-23 14:38
Hi, it seems you have pretty same configuration like me, the only difference is that I was running all the components inside Kubernetes.

Right now I'm running onehem-server on sameplace with oned due this bug, before that the problem was happening not every time but quite often.

I'm going to prepare new release soon, and I'll try to reproduce it again.

**Comment by rsmontero** [comment] 2020-10-28 10:52
WE'll close this for now. Thanks for the feedback!

**Closed by rsmontero** 2020-10-28 10:52 UTC
Labels: Category: Core & System, Community, Priority: Normal, Status: Accepted, Type: Bug

**Comment by kvaps** [comment] 2021-07-22 15:23
I just tried hem on 5.12.0.4, unfortunately the problem still persist.


```console
# ps aux
oneadmin  259448  2.3  0.3 3062500 261608 ?      Ssl  00:25  23:50 /usr/bin/ruby /usr/lib/one/onehem/onehem-server.rb
oneadmin  611917  0.0  0.0      0     0 ?        Z    02:21   0:00 [vps_task_write_] <defunct>
```

```console
# strace -p 259448
strace: Process 259448 attached
ppoll([{fd=3, events=POLLIN}], 1, NULL, NULL, 8
```

```console
# pstree -p 259448
ruby(259448)─┬─vps_task_write_(611917)
             ├─{ruby}(259784)
             ├─{ruby}(259785)
             ├─{ruby}(259786)
             ├─{ruby}(683853)
             ├─{ruby}(683859)
             ├─{ruby}(683871)
             ├─{ruby}(683882)
             ├─{ruby}(683896)
             ├─{ruby}(683897)
             ├─{ruby}(683905)
             ├─{ruby}(683935)
             ├─{ruby}(683949)
             └─{ruby}(923869)
```

the running hook process can't be killed even with `SIGKILL`:
```console
# kill -9 611917
# ps aux | grep 611917
oneadmin  611917  0.0  0.0      0     0 ?        Z    02:21   0:00 [vps_task_write_] <defunct>
```

@rsmontero any ideas?
