### ISSUE TITLE
LXD fails to cleanup context CD-ROM mount

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5103] opened 2020-09-22 14:33 UTC
**Description**
Same issue as #3389, still hapens with 5.12.4dev. Doesn't deal with CD-ROM left mounted and fails VM epilog, seen mainly on contextualization microenvs.

```
Mon Sep 21 22:01:19 2020 [Z0][VM][I]: New state is ACTIVE
Mon Sep 21 22:01:19 2020 [Z0][VM][I]: New LCM state is PROLOG
Mon Sep 21 22:01:19 2020 [Z0][VM][I]: New LCM state is BOOT
Mon Sep 21 22:01:19 2020 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/28/deployment.0
Mon Sep 21 22:01:19 2020 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Mon Sep 21 22:01:19 2020 [Z0][VMM][I]: ExitCode: 0
Mon Sep 21 22:01:19 2020 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: deploy: Processing disk 0
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: deploy: Using qcow2 mapper for /var/lib/one/datastores/0/28/disk.0
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: deploy: Mapping disk at /var/lib/lxd/storage-pools/default/containers/one-28/rootfs using device /dev/nbd4
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: deploy: Mounting /dev/nbd4p1 at /var/lib/lxd/storage-pools/default/containers/one-28/rootfs
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: deploy: Mapping disk at /var/lib/one/datastores/0/28/mapper/disk.1 using device /dev/loop4
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: deploy: Mounting /dev/loop4 at /var/lib/one/datastores/0/28/mapper/disk.1
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: deploy: --- Starting container ---
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: ExitCode: 0
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: ExitCode: 0
Mon Sep 21 22:01:20 2020 [Z0][VMM][I]: Successfully execute network driver operation: post.
Mon Sep 21 22:01:20 2020 [Z0][VM][I]: New LCM state is RUNNING
Mon Sep 21 22:01:31 2020 [Z0][VM][I]: New LCM state is SHUTDOWN
Mon Sep 21 22:01:32 2020 [Z0][LCM][I]: VM reported SHUTDOWN by the drivers
Mon Sep 21 22:01:32 2020 [Z0][VM][I]: New LCM state is EPILOG
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/lxd/cancel 'one-28' 'ubuntu1804-context-lxd-5-12-4-de7a6-0.test' 28 ubuntu1804-context-lxd-5-12-4-de7a6-0.test
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: --- Stopping container ---
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: Processing disk 0
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: Unknown /var/lib/one/datastores/0/28/disk.0: cannot open `/var/lib/one/datastores/0/28/disk.0' (No such file or directory)
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: image format,                     trying raw filesystem mapper
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: Unmapping disk at /var/lib/lxd/storage-pools/default/containers/one-28/rootfs
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: Umounting disk mapped at /dev/nbd4p1
Mon Sep 21 22:01:33 2020 [Z0][VMM][E]: shutdown: do_unmap: losetup: /dev/nbd4: failed to use device: No such device
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: /var/tmp/one/vmm/lxd/shutdown:50:in `<main>': Failed to dismantle container storage (RuntimeError)
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: ExitCode: 1
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: Failed to execute virtualization driver operation: cancel.
Mon Sep 21 22:01:33 2020 [Z0][VMM][E]: Error canceling VM
Mon Sep 21 22:01:33 2020 [Z0][LCM][E]: shutdown_failure_action, VM in a wrong state
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: Command execution failed (exit code: 1): /var/lib/one/remotes/tm/qcow2/delete ubuntu1804-context-lxd-5-12-4-de7a6-0.test:/var/lib/one//datastores/0/28 28 0
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: delete: Deleting /var/lib/one/datastores/0/28
Mon Sep 21 22:01:42 2020 [Z0][TM][E]: delete: Command "[ -e "/var/lib/one/datastores/0/28" ] || exit 0
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: 
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: times=10
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: function="rm -rf /var/lib/one/datastores/0/28"
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: 
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: count=1
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: 
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: ret=$($function)
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: error=$?
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: 
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: while [ $count -lt $times -a "$error" != "0" ]; do
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: sleep 1
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: count=$(( $count + 1 ))
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: ret=$($function)
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: error=$?
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: done
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: 
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: [ "x$error" = "x0" ]" failed: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][I]: rm: cannot remove '/var/lib/one/datastores/0/28/mapper/disk.1/context.sh': Read-only file system
Mon Sep 21 22:01:42 2020 [Z0][TM][E]: Error deleting /var/lib/one/datastores/0/28
Mon Sep 21 22:01:42 2020 [Z0][TM][E]: Error executing image transfer script: Error deleting /var/lib/one/datastores/0/28
Mon Sep 21 22:01:42 2020 [Z0][VM][I]: New LCM state is EPILOG_FAILURE
```

**Details**
 - Hypervisor: LXD
 - Version: 5.12.4dev

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment] 2020-09-24 07:07
Can't reproduce. Looking at the error section

```
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vmm/lxd/cancel 'one-28' 'ubuntu1804-context-lxd-5-12-4-de7a6-0.test' 28 ubuntu1804-context-lxd-5-12-4-de7a6-0.test
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: --- Stopping container ---
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: Processing disk 0
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: Unknown /var/lib/one/datastores/0/28/disk.0: cannot open `/var/lib/one/datastores/0/28/disk.0' (No such file or directory)
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: image format,                     trying raw filesystem mapper
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: Unmapping disk at /var/lib/lxd/storage-pools/default/containers/one-28/rootfs
Mon Sep 21 22:01:33 2020 [Z0][VMM][I]: shutdown: Umounting disk mapped at /dev/nbd4p1
Mon Sep 21 22:01:33 2020 [Z0][VMM][E]: shutdown: do_unmap: losetup: /dev/nbd4: failed to use device: No such device
```

Seems to be a bit different from #3389. In this case the shutdown driver action is looking for the disk transferred by the TM and for some reason, it can't be found. The command `file -L -s /var/lib/one/datastores/0/28/disk.0` is ran in this case.

**Comment by vholer** [comment] 2021-02-05 17:09
Note: Still appears in development (5.13.80), error message in this case same as in https://github.com/OpenNebula/one/issues/3389:

```
Thu Feb  4 21:26:25 2021 [Z0][VMM][E]: CANCEL
Thu Feb  4 21:26:25 2021 [Z0][LCM][E]: shutdown_failure_action, VM in a wrong state
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: Command execution failed (exit code: 1): /var/lib/one/remotes/tm/qcow2/delete ubuntu1804-context-lxd-5-13-80-66e74-0.test:/var/lib/one//datastores/0/2 2 0
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: delete: Deleting /var/lib/one//datastores/0/2
Thu Feb  4 21:26:34 2021 [Z0][TrM][E]: delete: Command "[ -e "/var/lib/one//datastores/0/2" ] || exit 0
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: 
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: times=10
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: function="rm -rf /var/lib/one//datastores/0/2"
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: 
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: count=1
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: 
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: ret=$($function)
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: error=$?
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: 
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: while [ $count -lt $times -a "$error" != "0" ]; do
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: sleep 1
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: count=$(( $count + 1 ))
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: ret=$($function)
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: error=$?
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: done
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: 
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: [ "x$error" = "x0" ]" failed: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/context.sh': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][I]: rm: cannot remove '/var/lib/one//datastores/0/2/mapper/disk.1/token.txt': Read-only file system
Thu Feb  4 21:26:34 2021 [Z0][TrM][E]: Error deleting /var/lib/one//datastores/0/2
Thu Feb  4 21:26:34 2021 [Z0][TrM][E]: Error executing image transfer script: Error deleting /var/lib/one//datastores/0/2
Thu Feb  4 21:26:34 2021 [Z0][VM][I]: New LCM state is EPILOG_FAILURE
```

**Closed** 2021-02-26 13:39 UTC
Labels: Category: LXD, Priority: Normal, Status: Accepted, Type: Bug
