### ISSUE TITLE
Editing ACLs on-the-fly in Sunstone for vOneCloud

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1179] opened 2017-11-20 11:14 UTC
---

Author Name: **Miguel Ángel Álvarez Cabrerizo** (Miguel Ángel Álvarez Cabrerizo)
Original Redmine Issue: 5019, https://dev.opennebula.org/issues/5019
Original Date: 2017-02-11

---

As requested in:
https://support.vonecloud.com/hc/en-us/community/posts/115000396705-Couple-of-Newbie-Questions

**Comment by rsmontero** [comment] 2017-12-05 14:27
duplicate of #721

**Closed by rsmontero** 2017-12-05 14:27 UTC
Labels: Category: Sunstone, Type: Backlog
