### ISSUE TITLE
Cannot boot VM with more than one scsi disk

### ISSUE THREAD

**Issue by joergludwig** [OpenNebula/one#2971] opened 2019-02-20 14:59 UTC
**Description**
Booting a VM with more than one scsi disk stops with an error message.
The error occurs with adapter "lsilogic" and "buslogic".
VMs with one scsi disk work. VMs with multiple virtio disks work as well.
We need scsi disks for trim support.

/var/log/one/oned.log:
```
LOG I 21 error: unsupported configuration: target must be 0 for controller model 'lsilogic'
```

Error shown in Sunstone:
```
Error deploying virtual machine: Could not create domain from /var/lib/one//datastores/0/21/deployment.20
```

Extract of /var/lib/one/datastores/0/21/deployment.20:
```
		<disk type='file' device='cdrom'>
			<source file='/var/lib/one//datastores/0/21/disk.0'/>
			<target dev='sda'/>
			<boot order='2'/>
			<readonly/>
			<driver name='qemu' type='raw' cache='none'/>
			<address type='drive' controller='0' bus='0' target='0' unit='0'/>
		</disk>
		<disk type='file' device='disk'>
			<source file='/var/lib/one//datastores/0/21/disk.4'/>
			<target dev='sdb'/>
			<driver name='qemu' type='qcow2' cache='none'/>
			<address type='drive' controller='0' bus='0' target='1' unit='0'/>
		</disk>
```

**To Reproduce**
Create a VM, add two scsi disks, boot. We have the machine type set to "q35" globally.

**Expected behavior**
VM should boot.

**Details**
 - Affected Component: Scheduler or Storage
 - Hypervisor: KVM
 - Version: 5.6.1-1
 - Machine: q35
 - Architecure: x86_64

**Additional context**
We think, the problem was introduced here: https://github.com/OpenNebula/one/commit/e164fde85f4459add2e8007ebcf15da5d045d514

See also:
https://github.com/libvirt/libvirt/blob/master/src/qemu/qemu_command.c#L5103

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sergiojvg** [comment] 2019-02-22 23:34
Fixed on 5.8.

**Comment by joergludwig** [comment] 2019-02-25 14:26
Thanks! :)

**Comment by joergludwig** [comment] 2019-03-09 16:56
Still exactly the same problem in OpenNebula 5.8.0-1.
I even rebooted the server and set machine type back to "pc" just to be sure.

/var/log/one/oned.log:
```
LOG I 21 error: unsupported configuration: target must be 0 for controller model 'lsilogic'
```

Extract of /var/lib/one/datastores/0/21/deployment.31:
```
		<disk type='file' device='disk'>
			<source file='/var/lib/one//datastores/0/21/disk.1'/>
			<target dev='sda'/>
			<boot order='1'/>
			<driver name='qemu' type='qcow2' cache='none' discard='unmap'/>
			<address type='drive' controller='0' bus='0' target='0' unit='0'/>
		</disk>
		<disk type='file' device='disk'>
			<source file='/var/lib/one//datastores/0/21/disk.4'/>
			<target dev='sdb'/>
			<driver name='qemu' type='qcow2' cache='none' discard='unmap'/>
			<address type='drive' controller='0' bus='0' target='1' unit='0'/>
		</disk>
```

**Comment by tinova** [comment] 2019-03-26 09:53
we'll look into this, thanks for the feedback

**Comment by tinova** [comment] 2019-03-26 09:54
can you send us the output of "onevm show -x 21"?

**Comment by joergludwig** [comment] 2019-03-26 17:49
As my VM 21 created hundreds of pages of xml output, I created a new clean VM with two scsi disks to show the problem:

[onevm_show_208.xml.txt](https://github.com/OpenNebula/one/files/3009503/onevm_show_208.xml.txt)
[208.log](https://github.com/OpenNebula/one/files/3009509/208.log)
[deployment.1.txt](https://github.com/OpenNebula/one/files/3009510/deployment.1.txt)

**Comment by sergiojvg** [comment] 2019-04-03 22:26
We have reproduced the issue.

**Comment by tinova** [comment] 2019-04-04 14:53
Need to figure out how to set target 0 if bus adapter is either "lsilogic" and "buslogic".

**Comment by dealfonso** [comment] 2019-04-17 08:07
Hi,
same error here...

The deployment file that ONE has created is (but it does not work)
```
...
                <disk type='file' device='disk'>
                        <source file='/var/lib/one//datastores/0/33153/disk.0'/>
                        <target dev='sda'/>
                        <driver name='qemu' type='qcow2' cache='none'/>
                        <address type='drive' controller='0' bus='0' target='0' unit='0'/>
                </disk>
                <disk type='file' device='disk'>
                        <source file='/var/lib/one//datastores/0/33153/disk.1'/>
                        <target dev='sdb'/>
                        <driver name='qemu' type='raw' cache='none'/>
                        <address type='drive' controller='0' bus='0' target='1' unit='0'/>
                </disk>
                <disk type='file' device='disk'>
                        <source file='/var/lib/one//datastores/0/33153/disk.2'/>
                        <target dev='sdc'/>
                        <driver name='qemu' type='raw' cache='none'/>
                        <address type='drive' controller='0' bus='0' target='2' unit='0'/>
                </disk>
...
```
If I move the value in "target" to "unit", it works (and also the units are properly mapped in the VM, as reported in sunstone)

```
                <disk type='file' device='disk'>
                        <source file='/var/lib/one//datastores/0/33153/disk.0'/>
                        <target dev='sda'/>
                        <driver name='qemu' type='qcow2' cache='none'/>
                        <address type='drive' controller='0' bus='0' target='0' unit='0'/>
                </disk>
                <disk type='file' device='disk'>
                        <source file='/var/lib/one//datastores/0/33153/disk.1'/>
                        <target dev='sdb'/>
                        <driver name='qemu' type='raw' cache='none'/>
                        <address type='drive' controller='0' bus='0' target='0' unit='1'/>
                </disk>
                <disk type='file' device='disk'>
                        <source file='/var/lib/one//datastores/0/33153/disk.2'/>
                        <target dev='sdc'/>
                        <driver name='qemu' type='raw' cache='none'/>
                        <address type='drive' controller='0' bus='0' target='0' unit='2'/>
                </disk>
```

**Comment by xorel** [comment] 2019-09-05 15:51
I can't reproduce the issues. Can you verify you have `virtio_scsi_queues` enabled? Either globaly in _vmm_exec_kvm.conf_ or in VM Template 
```
FEATURES = [
  VIRTIO_SCSI_QUEUES = "1" ]
```

**Comment by joergludwig** [comment] 2019-09-09 15:38
Perfect, this option fixes our issue. Thank you very much!

Is there a reason, it is not enabled by default?
https://github.com/OpenNebula/one/blob/master/src/vmm_mad/exec/vmm_exec_kvm.conf#L35

**Comment by dealfonso** [comment] 2019-09-10 07:14
Hi,
that option also fixes the issue here. it is a weird behavior if not enabled. Where is it documented? I have noticed that such option is not available in older releases...

**Comment by xorel** [comment] 2019-09-16 12:28
PRs:
* one https://github.com/OpenNebula/one/pull/3709 to master
* docs https://github.com/OpenNebula/docs/pull/762 to master

**Closed** 2019-09-17 14:31 UTC
Labels: Category: Drivers - VM, Community, Priority: Normal, Status: Accepted, Type: Bug

**Comment by k51312** [comment] 2020-01-20 08:46
hi，
   i have a trouble in create vm with scsi disk, for the guest os can't start 

[root@NSG ~]# virsh list --all
 Id    Name                           State
----------------------------------------------------
 2     root-vsys_scsi-vm1             running

[root@NSG ~]# virsh dumpxml root-vsys_scsi-vm1
<domain type='kvm' id='2'>
  <name>root-vsys_scsi-vm1</name>
  <uuid>019d35aa-786b-403e-bb2d-0c3aa419191d</uuid>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <memoryBacking>
    <hugepages>
      <page size='2048' unit='KiB' nodeset='0'/>
    </hugepages>
  </memoryBacking>
  <vcpu placement='static'>2</vcpu>
  <numatune>
    <memory mode='strict' nodeset='0'/>
  </numatune>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-3.0'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>Broadwell</model>
    <vendor>Intel</vendor>
    <topology sockets='1' cores='2' threads='1'/>
    <feature policy='require' name='vme'/>
    <feature policy='require' name='ss'/>
    <feature policy='require' name='f16c'/>
    <feature policy='require' name='rdrand'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='require' name='arat'/>
    <feature policy='require' name='tsc_adjust'/>
    <feature policy='require' name='xsaveopt'/>
    <feature policy='require' name='abm'/>
    <feature policy='require' name='topoext'/>
    <feature policy='disable' name='erms'/>
    <numa>
      <cell id='0' cpus='0-1' memory='4194304' unit='KiB' memAccess='shared'/>
    </numa>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/local/bin/qemu-system-x86_64</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/home/root-vsys_scsi-vm1.qcow2'/>
      <backingStore/>
      <target dev='**_sda_**' bus='**_scsi_**'/>
      <alias name='scsi0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='usb' index='0' model='piix3-uhci'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'>
      <alias name='pci.0'/>
    </controller>
    <controller type='scsi' index='0' model='lsilogic'>
      <alias name='scsi0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </controller>
    <interface type='vhostuser'>
      <mac address='00:04:00:40:03:11'/>
      <source type='unix' path='/secgate/var/run/vh-1-64-0-3-1-1' mode='client'>
        <reconnect enabled='yes' timeout='60'/>
      </source>
      <model type='virtio'/>
      <driver queues='2'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <interface type='vhostuser'>
      <mac address='00:04:00:40:03:12'/>
      <source type='unix' path='/secgate/var/run/vh-1-64-0-3-1-2' mode='client'>
        <reconnect enabled='yes' timeout='60'/>
      </source>
      <model type='virtio'/>
      <driver queues='2'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </interface>
    <interface type='vhostuser'>
      <mac address='00:04:00:40:03:13'/>
      <source type='unix' path='/secgate/var/run/vh-1-64-0-3-1-3' mode='client'>
        <reconnect enabled='yes' timeout='60'/>
      </source>
      <model type='virtio'/>
      <driver queues='2'/>
      <alias name='net2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </interface>
    <interface type='vhostuser'>
      <mac address='00:04:00:40:03:14'/>
      <source type='unix' path='/secgate/var/run/vh-1-64-0-3-1-4' mode='client'>
        <reconnect enabled='yes' timeout='60'/>
      </source>
      <model type='virtio'/>
      <driver queues='2'/>
      <alias name='net3'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
    <input type='mouse' bus='ps2'>
      <alias name='input0'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input1'/>
    </input>
    <graphics type='vnc' port='5900' autoport='yes' listen='0.0.0.0'>
      <listen type='address' address='0.0.0.0'/>
    </graphics>
    <video>
      <model type='cirrus' vram='16384' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <memballoon model='virtio'>
      <stats period='30'/>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='dynamic' model='dac' relabel='yes'>
    <label>+0:+0</label>
    <imagelabel>+0:+0</imagelabel>
  </seclabel>
</domain>

then the vm can success to create ,but when i enter into the guest os ,found the guest fail to start
![scsi-fail-4](https://user-images.githubusercontent.com/18366857/72711227-90024f80-3ba3-11ea-9b6e-2fba30c76dc3.png)
![scsi-fail-3](https://user-images.githubusercontent.com/18366857/72711231-909ae600-3ba3-11ea-867c-69f70a176b14.png)
![scsi-fail-2](https://user-images.githubusercontent.com/18366857/72711233-91337c80-3ba3-11ea-9100-e5918a7ce62a.png)
![scsi-fail-1](https://user-images.githubusercontent.com/18366857/72711234-91cc1300-3ba3-11ea-9976-d20ed02e30d3.png)

my centos7 kernel: linux-3.10.0-693.17.1.el7.x86_64 ,this kernel has reduced lots of parameters.
this mybe my host kernel .config has some problem, how should i config my kernel .config ??

                thanks

**Comment by jirutka** [comment] 2023-10-26 21:17
I’m experiencing the same issue even on OpenNebula 6.6.0! :angry:
