### ISSUE TITLE
Sunstone image size conversion 

### ISSUE THREAD

**Issue by agemuend** [OpenNebula/one#5644] opened 2021-11-25 09:01 UTC
**Description**
We have a bunch of images that have 

`<SIZE>100000</SIZE>`

in their template. Since the Upgrade to 5.12.10, we cannot instantiate a machine with those images, without changing the image size input field to MB first. The default is to show the size in GB, which divides the value by 1024, so it displays 97,65625 GB. With that value, you cannot submit the form because it expects an integer. 

**To Reproduce**
Create an image with a size that is not divisible by 1024, try to instantiate it with Sunstone.

**Expected behavior**
The best behaviour would probably be to switch to MB automatically when the size is not evenly divisible. 

**Details**
 - Affected Component: Sunstone
 - Hypervisor: KVM
 - Version: 5.12.10

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by agemuend** [comment] 2021-11-30 09:32
I just noticed that this only happens if its a USER_INPUT, not in the admin view.

**Comment by agemuend** [comment] 2022-04-01 12:42
Ping?

**Comment by FrederickBor** [comment] 2022-06-28 08:55
Hello @agemuend,

Could you please provide the template that you are trying to instantiate?

Also if you can send a screenshot of the USER_INPUT that fails it would be helpful.

Regards,
Frederick

**Comment by agemuend** [comment] 2022-07-12 08:33
@FrederickBor 
You can reproduce it with any template whatsoever, the only necessary parameter is the line I quoted above: 

`<SIZE>100000</SIZE>`

The same happens with other integers not evenly divisible by 1024. It seems to be a simple frontend javascript error in the User View.

**Comment by FrederickBor** [comment] 2022-07-14 09:12
Hi,

We will close this issue as we cannot reproduce it in v6.4.
Please update to the latest version and feel free to reopen it if you can reproduce it again.

Regards,
Frederick

**Closed by FrederickBor** 2022-07-14 09:12 UTC
Labels: Status: Pending, Category: Sunstone, Type: Bug
