### ISSUE TITLE
[FSunstone] Regular user register image URL - wrong DEV_PREFIX value with URL image

### ISSUE THREAD

**Issue by dann1** [OpenNebula/one#6130] opened 2023-02-13 21:19 UTC
**Description**
When creating an image whose source is a URL, the resulting image template will contain `DEV_PREFIX=path`

![image](https://user-images.githubusercontent.com/16429804/218576364-f7b87279-df7d-4ee9-b0c7-857647c27841.png)

The image also fails to be deleted even though the same user was able to create it. This is a all performed as a non oneadmin user.

**To Reproduce**
As a regular user, create an image using a URL as the source

**Expected behavior**
- DEV_PREFIX should contain `vd` or `sd`, definitely not `path`
- The image should be deletable afterwards

**Details**
 - Affected Component: [e.g. Sunstone, Scheduler, or Storage]
 - Hypervisor: [e.g. KVM]
 - Version: [e.g. 5.4.12 or development]

**Additional context**
When instantiating a VM with this image, the VM will result in the error

```log
Tue Jan 24 18:35:09 2023: DEPLOY: error: Failed to create domain from /var/lib/one//datastores/100/8340/deployment.0 error: XML error: Unknown disk name ‘patha’ and no address specified Could not create domain from /var/lib/one//datastores/100/8340/deployment.0 ExitCode: 255
```

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by vichansson** [comment] 2023-06-28 07:49
Duplicate of OpenNebula/One#6214

**Closed as completed** 2023-06-28 10:14 UTC
Labels: Category: Sunstone, Status: Accepted, Priority: Normal
