### ISSUE TITLE
Sunstone (sometimes) doesn't allow to switch between Wizard / Advanced

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#5038] opened 2020-08-17 15:48 UTC
[Note: I believe I must be just looking wrong if I can't find this problem filed, as IMHO Sunstone suffers from this misbehavior for long years. Feel free to close it as duplicate if there is issue already, sorry for my blind eyes.]

**Description**

It can happen (and happens often esp. when user opens multiple tabs with same Sunstone) that it's not possible to switch between Wizard / Advanced edit views until Sunstone browser window is fully reloaded. Happens for all types of objects which can be edited (not just VM template). See:

![simplescreenrecorder-2020-08-17_17 33 42](https://user-images.githubusercontent.com/414850/90414831-906ab680-e0b0-11ea-9eba-952a2d6ff06e.gif)

**To Reproduce**
I don't have precise steps, just use the Sunstone for some time. Opening in multiple windows most likely triggers the misbehaviour.

**Details**
 - Affected Component: Sunstone
 - Version: 5.12.2 (but affected are 

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment] 2021-07-27 15:55
cannot reproduce this, anyone has a list of steps to correctly reproduce the issue? developer console output when the problem happens can prove useful as well.

**Comment by kvaps** [comment] 2021-08-02 12:29
I just faced this issue today on 5.12.0.5. Haven't recorded any logs, sorry :-/

**Comment by jloboescalona2** [comment] 2021-08-02 12:33
Can you tell us how to reproduce the error? 
Would you know if that log would have characters other than UTF8?

**Comment by tinova** [comment] 2021-09-06 16:04
closing until more info is provided to reproduce the issue

**Closed by tinova** 2021-09-06 16:04 UTC
Labels: Category: Sunstone, Type: Bug, Status: Accepted, Priority: Normal
