### ISSUE TITLE
VM quotas per VM state

### ISSUE THREAD

**Issue by OpenNebulaSupport** [OpenNebula/one#1805] opened 2018-02-27 17:03 UTC
# Enhancement Request
## Description

VM quotas now apply to ACTIVE VMs (running, poweroff, etc)

## Use case

Admin wants to allow 20 VMs to a particular user, but only 5 in running. 15 can be in poweroff.

## Interface Changes

Changes in Sunstone in CLI to accommodate quotas definition and display

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment] 2018-03-16 07:24
Related: #720

**Comment by feldsam** [comment] 2018-11-01 16:54
@juanmont Hello, looks like this implemented in 5.6, right? Because I have problems with Running VM quota. Should I open bug report or deal with it here?

**Comment by vholer** [comment] 2019-09-08 00:30
I don't understand the request precisely, but the way it's now implemented has a bug or it's just my misunderstanding how RUNNING quotas are supposed to work.

I'm seeing a problem that counters in RUNNING quotas are always increased on VM create, no matter if the VM has any chances for deployment (e.g., no capacity). The simplest case is creating VMs in on-hold state, such VMs are all counted into RUNNING quotas. That's wrong.

The RUNNING counters are properly decreased when machine is power-off. So it was expected to work as one would expect, but obviously RUNNING quotas are increased too early.

Steps to reproduce:
- set quota on RUNNING metric, e.g. RUNNING_VMS=3
- instantiate 5 VMs in on-hold state
- 3 passes, 2 fails --> all shoud pass
- instantiate 5 VMs
- 3 passes, 2 fails --> all should be created, but just 3 should be considered to deploy

To me, this issue is a bug as the current state isn't intuitive.

**Comment by rsmontero** [comment] 2020-03-02 19:13
Hi guys, this is stated in the documentation:

```Running quotas will be increased or decreased depending on the state of the Virtual Machine. The states in which the machine is counted as ACTIVE “Running” are ACTIVE , HOLD, PENDING and CLONING.```

So it is working as expected. A bit rationale behind this. 

Quotas are used as an admission control facility, this means the quotas needs to be evaluated when the resource is created, it may impose some delay between pending to active but using other semantics would require to spread the logic across components e.g. scheduler to not deploy VMs for example. Also, from the user point of view, it may be better to know at deployment time if the VM is going to be deployed or not.

So I agree this time with @feldsam, 5 RUNNING 15 POWEROFF is supported by RUNNING quotas. 

I'm closing this one:
1. @feldsam if it is not working for you as it is described in the documentation please fill an issue for this,
2. @vholer we can create an issue in the backlog to extend the semantics if needed

**Closed by rsmontero** 2020-03-02 19:13 UTC
Labels: Category: CLI, Category: Core & System, Category: Sunstone, Sponsored, Status: Accepted, Type: Bug
