### ISSUE TITLE
Sunstone: User can see vms id who uses image even if he have no access to them

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1388] opened 2017-11-20 12:10 UTC
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5457, https://dev.opennebula.org/issues/5457
Original Date: 2017-10-13
Original Assignee: Abel Coronado

---

See screenshot for more detail:

!img.png!

**Comment by OpenNebulaProject** [comment] 2017-11-20 12:10
---

Original Redmine Comment
Author Name: **kvaps kvaps** (kvaps kvaps)
Original Date: 2017-10-19T10:24:22Z

---

This question to you, isn't it?

**Comment by tinova** [comment] 2020-03-03 11:55
cannot reproduce this, closing until more feedback is provided.

**Comment by kvaps** [comment] 2020-03-03 12:21
@tinova, steps to reproduce:

* Create public template with image
* Allow users to use it
* Users will able to instantiate VMs from it but they also will able to see whole list of VM IDs of other users who uses the same image

**Comment by kvaps** [comment] 2020-03-03 12:24
The same problem will occure if you allow users to use some specific images datastore, then user will see the iamges IDs of the other users:

![image](https://user-images.githubusercontent.com/7556217/75775417-3c625480-5d52-11ea-832e-052e2fca98d5.png)

**Comment by tinova** [comment] 2020-03-03 12:25
ok, thanks! we'll try to reproduce

**Comment by sbbarragan** [comment] 2020-03-11 15:49
PRs to merge:
• one: #4345 
• docs: OpenNebula/docs/pull/990

**Closed** 2020-03-11 16:02 UTC
Labels: Category: Sunstone, Community, Status: Accepted, Type: Bug
