### ISSUE TITLE
Missing delete_vlan_dev function on bridge driver

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#4006] opened 2019-11-29 14:26 UTC
**Description**
When LXD VM is stopped, VNM driver clean opration failed

**To Reproduce**
Start LXD VM using Netowork with VN_MAD == bridge, then shutdown VM 

**Expected behavior**
VNM clean operation should success 

**Details**
 - Affected Component: VNM
 - Hypervisor: LXD
 - Version: 5.10

**Additional context**
```
Fri Nov 29 09:17:56 2019 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: shutdown: --- Stopping container ---
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: shutdown: Processing disk 0
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: shutdown: Using raw filesystem mapper for /var/lib/one/datastores/105/77/disk.0
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: shutdown: Unmapping disk at /var/lib/lxd/storage-pools/default/containers/one-77/rootfs
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: shutdown: Umounting disk mapped at /dev/loop4
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: shutdown: Unmapping disk at /var/lib/one/datastores/105/77/mapper/disk.1
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: shutdown: Umounting disk mapped at /dev/loop5
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: ExitCode: 0
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: Successfully execute virtualization driver operation: shutdown.
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vnm/bridge/clean
Fri Nov 29 09:17:59 2019 [Z0][VMM][E]: clean: delete_vlan_dev function not implemented.
Fri Nov 29 09:17:59 2019 [Z0][VMM][E]: clean: exit
Fri Nov 29 09:17:59 2019 [Z0][VMM][E]: clean: ["/var/tmp/one/vnm/vlan.rb:83:in `exit'", "/var/tmp/one/vnm/vlan.rb:83:in `delete_vlan_dev'", "/var/tmp/one/vnm/vlan.rb:120:in `block in deactivate'", "/var/tmp/one/vnm/vnm_driver.rb:81:in `block in process'", "/var/tmp/one/vnm/vm.rb:64:in `block in each_nic'", "/var/tmp/one/vnm/vm.rb:63:in `each'", "/var/tmp/one/vnm/vm.rb:63:in `each_nic'", "/var/tmp/one/vnm/vnm_driver.rb:84:in `process'", "/var/tmp/one/vnm/vlan.rb:95:in `deactivate'", "/var/tmp/one/vnm/bridge/clean:30:in `<main>'"]
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: ExitCode: 1
Fri Nov 29 09:17:59 2019 [Z0][VMM][I]: Failed to execute network driver operation: clean.
Fri Nov 29 09:17:59 2019 [Z0][VMM][E]: Error shutting down VM: bridge: -
Fri Nov 29 09:17:59 2019 [Z0][VM][I]: New LCM state is RUNNING
```

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by dann1** [comment] 2019-11-29 17:58
I'm not able to reproduce the issue

```
Fri Nov 29 16:17:03 2019 [Z0][VM][I]: New state is ACTIVE
Fri Nov 29 16:17:03 2019 [Z0][VM][I]: New LCM state is PROLOG
Fri Nov 29 16:17:05 2019 [Z0][VM][I]: New LCM state is BOOT
Fri Nov 29 16:17:05 2019 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/5/deployment.0
Fri Nov 29 16:17:06 2019 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Fri Nov 29 16:17:07 2019 [Z0][VMM][I]: ExitCode: 0
Fri Nov 29 16:17:07 2019 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: deploy: Processing disk 0
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: deploy: Using qcow2 mapper for /var/lib/one/datastores/0/5/disk.0
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: deploy: Mapping disk at /var/lib/lxd/storage-pools/default/containers/one-5/rootfs using device /dev/nbd0
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: deploy: Mounting /dev/nbd0 at /var/lib/lxd/storage-pools/default/containers/one-5/rootfs
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: deploy: Mapping disk at /var/lib/one/datastores/0/5/mapper/disk.1 using device /dev/loop0
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: deploy: Mounting /dev/loop0 at /var/lib/one/datastores/0/5/mapper/disk.1
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: deploy: --- Starting container ---
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: ExitCode: 0
Fri Nov 29 16:17:08 2019 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Fri Nov 29 16:17:09 2019 [Z0][VMM][I]: ExitCode: 0
Fri Nov 29 16:17:09 2019 [Z0][VMM][I]: Successfully execute network driver operation: post.
Fri Nov 29 16:17:09 2019 [Z0][VM][I]: New LCM state is RUNNING
Fri Nov 29 16:17:14 2019 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: shutdown: --- Stopping container ---
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: shutdown: Processing disk 0
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: shutdown: Using qcow2 mapper for /var/lib/one/datastores/0/5/disk.0
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: shutdown: Unmapping disk at /var/lib/lxd/storage-pools/default/containers/one-5/rootfs
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: shutdown: Umounting disk mapped at /dev/nbd0
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: shutdown: Unmapping disk at /var/lib/one/datastores/0/5/mapper/disk.1
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: shutdown: Umounting disk mapped at /dev/loop0
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: ExitCode: 0
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: Successfully execute virtualization driver operation: cancel.
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: ExitCode: 0
Fri Nov 29 16:17:23 2019 [Z0][VMM][I]: Successfully execute network driver operation: clean.
Fri Nov 29 16:17:23 2019 [Z0][VM][I]: New state is POWEROFF
Fri Nov 29 16:17:23 2019 [Z0][VM][I]: New LCM state is LCM_INIT
```

Also, it doesn't seem to be LXD related:

```
019 [Z0][VMM][E]: clean: delete_vlan_dev function not implemented.
Fri Nov 29 09:17:59 2019 [Z0][VMM][E]: clean: exit
Fri Nov 29 09:17:59 2019 [Z0][VMM][E]: clean: ["/var/tmp/one/vnm/vlan.rb:83:in `exit'", "/var/tmp/one/vnm/vlan.rb:83:in `delete_vlan_dev'", "/var/tmp/one/vnm/vlan.rb:120:in `block in deactivate'", "/var/tmp/one/vnm/vnm_driver.rb:81:in `block in process'", "/var/tmp/one/vnm/vm.rb:64:in `block in each_nic'", "/var/tmp/one/vnm/vm.rb:63:in `each'", "/var/tmp/one/vnm/vm.rb:63:in `each_nic'", "/var/tmp/one/vnm/vnm_driver.rb:84:in `process'", "/var/tmp/one/vnm/vlan.rb:95:in `deactivate'", "/var/tmp/one/vnm/bridge/clean:30:in `<main>'"]
Fri Nov 29 09:17:59 20
```

Maybe a bad network hook ?

**Comment by dann1** [comment] 2019-12-09 16:48
Probably a bad network hook according to the dummy function being called, not LXD related. We can reopen if needed.

**Comment by webtobesocial** [comment] 2019-12-13 01:50
Hi I installed Opennebula 5.10 on Ubuntu 18.4 today.. Then I created a VM on a KVM host and after setting up a VM template and instantiating I installed Ubuntu 18.04 on the VM when trying to shutdown the VM I got these errors... Any idea?


`brctl show`
```
bridge name	bridge id		    STP enabled	interfaces
br0		        8000.6a291840844b	no		vlan2
virbr0		8000.5254002b56b1	yes		virbr0-nic
```

Log output from the VM in Sunstone frontend

```
Fri Dec 13 01:26:09 2019 [Z0][VM][I]: New state is ACTIVE
Fri Dec 13 01:26:09 2019 [Z0][VM][I]: New LCM state is PROLOG
Fri Dec 13 01:26:46 2019 [Z0][VM][I]: New LCM state is BOOT
Fri Dec 13 01:26:46 2019 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/10/deployment.0
Fri Dec 13 01:26:47 2019 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Fri Dec 13 01:26:48 2019 [Z0][VMM][I]: ExitCode: 0
Fri Dec 13 01:26:48 2019 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Fri Dec 13 01:26:49 2019 [Z0][VMM][I]: ExitCode: 0
Fri Dec 13 01:26:49 2019 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Fri Dec 13 01:26:50 2019 [Z0][VMM][I]: ExitCode: 0
Fri Dec 13 01:26:50 2019 [Z0][VMM][I]: Successfully execute network driver operation: post.
Fri Dec 13 01:26:50 2019 [Z0][VM][I]: New LCM state is RUNNING
Fri Dec 13 01:33:07 2019 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Fri Dec 13 01:33:08 2019 [Z0][VMM][I]: ExitCode: 0
Fri Dec 13 01:33:08 2019 [Z0][VMM][I]: Successfully execute virtualization driver operation: cancel.
Fri Dec 13 01:33:09 2019 [Z0][VMM][I]: Command execution fail: cat << EOT | /var/tmp/one/vnm/bridge/clean
Fri Dec 13 01:33:09 2019 [Z0][VMM][E]: clean: delete_vlan_dev function not implemented.
Fri Dec 13 01:33:09 2019 [Z0][VMM][E]: clean: exit
Fri Dec 13 01:33:09 2019 [Z0][VMM][E]: clean: ["/var/tmp/one/vnm/vlan.rb:83:in `exit'", "/var/tmp/one/vnm/vlan.rb:83:in `delete_vlan_dev'", "/var/tmp/one/vnm/vlan.rb:120:in `block in deactivate'", "/var/tmp/one/vnm/vnm_driver.rb:81:in `block in process'", "/var/tmp/one/vnm/vm.rb:64:in `block in each_nic'", "/var/tmp/one/vnm/vm.rb:63:in `each'", "/var/tmp/one/vnm/vm.rb:63:in `each_nic'", "/var/tmp/one/vnm/vnm_driver.rb:84:in `process'", "/var/tmp/one/vnm/vlan.rb:95:in `deactivate'", "/var/tmp/one/vnm/bridge/clean:30:in `<main>'"]
Fri Dec 13 01:33:09 2019 [Z0][VMM][I]: ExitCode: 1
Fri Dec 13 01:33:09 2019 [Z0][VMM][I]: Failed to execute network driver operation: clean.
Fri Dec 13 01:33:09 2019 [Z0][VMM][E]: Error canceling VM: bridge: -
Fri Dec 13 01:33:09 2019 [Z0][VM][I]: New LCM state is RUNNING
Fri Dec 13 01:33:09 2019 [Z0][LCM][I]: Fail to shutdown VM. Assuming that the VM is still RUNNING (will poll VM).
```

And on the host

`ip a s`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 46:f1:8d:4a:f1:fb brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/22 brd xx.xx.xx.255 scope global dynamic ens3
       valid_lft 2675127sec preferred_lft 2675127sec
    inet6 fe80::44f1:8dff:fe4a:f1fb/64 scope link 
       valid_lft forever preferred_lft forever
3: ens6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 46:f1:8d:4a:f1:fc brd ff:ff:ff:ff:ff:ff
    inet6 fe80::44f1:8dff:fe4a:f1fc/64 scope link 
       valid_lft forever preferred_lft forever
4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 6a:29:18:40:84:4b brd ff:ff:ff:ff:ff:ff
    inet6 fe80::6829:18ff:fe40:844b/64 scope link 
       valid_lft forever preferred_lft forever
5: vlan1@ens6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 46:f1:8d:4a:f1:fc brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/24 brd xx.xx.xx.255 scope global vlan1
       valid_lft forever preferred_lft forever
    inet6 fe80::44f1:8dff:fe4a:f1fc/64 scope link 
       valid_lft forever preferred_lft forever
6: vlan2@ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP group default qlen 1000
    link/ether 46:f1:8d:4a:f1:fb brd ff:ff:ff:ff:ff:ff
    inet xx.xx.xx.xx/32 scope global vlan2
       valid_lft forever preferred_lft forever
    inet6 fe80::44f1:8dff:fe4a:f1fb/64 scope link 
       valid_lft forever preferred_lft forever
7: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:2b:56:b1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
8: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:2b:56:b1 brd ff:ff:ff:ff:ff:ff
```

Please reopen the issue. I guess

**Comment by feldsam** [comment] 2019-12-13 08:08
Nice to hear this, I don't have time to prove it is a bug.

**Comment by dann1** [comment] 2019-12-15 01:57
The bug happens when virtual network is using `VNM_MAD = fw/bridge` and `keep_empty_bridge` isn't `true`. When [this PR](https://github.com/OpenNebula/one/commit/cc2356d71ad0205b9d31b44f397b20cc7b8df9d1) got merged it didn't add the extracted function to the `NoVLANDriver` child class and the deactivate action triggered the dummy `VLANDriver` function which throws an error.

**Closed** 2019-12-16 14:27 UTC
Labels: Category: Drivers - Network, Status: Accepted, Type: Bug
