### ISSUE TITLE
Live migration-over-SSH

### ISSUE THREAD

**Issue by myjapan** [OpenNebula/one#5271] opened 2021-03-01 10:00 UTC
**Description**
Integrate and support officially the live migration-over-SSH method developed by Leroy Förster, Paul Jost, Mark Zealey
https://gist.github.com/mzealey/0cac6328c8bbc86c733a72e7a6af89a7

**Use case**
OpenNebula deployment who don't use shared storage needs a way to drain the VMs from the node and perform OS updates and reboots

**Additional Context**
This feature could give to Infrastructure DevOps the possibility to automate updates (example via Ansible) with a minimal disruption on the VMs

## Progress Status
- [ ] Branch created
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment] 2021-03-01 10:10
Duplicate of https://github.com/OpenNebula/one/issues/1644

**Comment by al3xhh** [comment] 2021-11-04 11:47
Closing this.

**Closed by al3xhh** 2021-11-04 11:47 UTC
