### ISSUE TITLE
Do not instantiate VM if IP is allocated

### ISSUE THREAD

**Issue by FlorianHeigl** [OpenNebula/one#1635] opened 2018-01-05 22:49 UTC
# Bug Report
## Version of OpenNebula

- [x] 5.2.2
- [x] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

(anything >5.4.0 is your business)

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [x] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [x] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [x] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

You can instantiate a VM even though it will not be able to launch / be refused later due to the IP resource being allocated already

### Expected Behavior
To have sunstone / one*cli validate this on first step, and tell me the IP is already allocated instead of doing something that will not work.

### Actual Behavior
We can submit it from Sunstone (which knows all IPs that are currently allocated) and then, later we get a failure.

## How to reproduce

Default behaviour

# Enhancement Request
## Interface Changes

 

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by juanmont** [comment] 2018-04-04 13:51
Hello! I'm trying to reproduce this bug but I can't reproduce it, I did these step:

1. I have created a new Virtual Machine with a NIC.
2. Copy the Allocate IP for the first Machine.
3. I have tried to instantiate a new VM but I forced the IP with the same IP and OpenNebula return an error (Cannot get IP/MAC lease from virtual network 0.).
4. Also I tried to attach new nic over a running VM but OpenNebula return the same error.

I'm working with last version of OpenNebula.

**Comment by FlorianHeigl** [comment] 2018-04-04 13:55
So if you click instantiate, does it not let you do that and return the error right away (that would be useful), or at a later point as a popup or failure to launch?

**Comment by juanmont** [comment] 2018-04-04 14:15
OpenNebula return me an error when I click on instantiate in Sunstone with a JGrowl Message.

The error is: Cannot get IP/MAC lease from virtual network 0.

**Comment by FlorianHeigl** [comment] 2018-04-04 14:17
Does it let you do the click (and close the dialogue etc) or does it block the clicking already and show the message as you try?
(Like in almost any software made in this decade)

**Comment by hydro-b** [comment] 2018-04-04 14:26
On Wed, Apr 04, 2018 at 02:17:57PM +0000, Florian Heigl wrote:
> Does it let you do the click (and close the dialogue etc) or does it
> block the clicking already and show the message as you try?  (Like in
> almost any software made in this decade)

I think the point Florian tries to make here is that the "instantiate"
button should be "greyed" out or something like that, instead of having
to try to instantiate, and then get an error.

@Florian: I had some discussion with ONE devs in the past. Doing stuff
like that would need synchronous API calls, which can be expensive with
many clients (doensn't scale).

Gr. stefan

**Comment by FlorianHeigl** [comment] 2018-04-04 14:29
@hydro-b thanks for translating, I think that's what I mean.
Right now it scales over the wasted time of the end-users which is something that hurts the project more than a potential performance issue. IMO. Also, idk, even AWS can do it and I think they have a few clients. We need to weed out those things or find smarter solutions from them. That's why I started reporting the bugs that have always been just a bit annoying to us but driving away less enthusiastic people. not solving that for years gets noticed.

**Comment by rsmontero** [comment] 2018-04-09 13:59
Hi guys,

We want to consolidate this logic as much as possible for multiple reasons. The more this check spreads across components the more difficult is to maintain the code. Note that this will require to add checks in Sunstone, in Flow, in any language binding.... We believe that at the end this consistency in the interfaces and behavior is better, and if we replicate this code across components is something difficult to maintain and update.  We had this kind of problems in the past when the logic was replicated in the interface and in the core and is something we want to avoid as a design principle.

Note also that this is a multi-tenancy system, and multiple users are going to make concurrent requests so even if you make the check client-side, this needs to be validated server-side.

However, this check should be rather quick and in fact the system is not going to let you create something that is not going to work. Finally, we may explore another approaches to your implementation. For example user-based reservations may come in handy as is a user-controlled address space. (This is something we want to improve in 5.8 as we couldn't make it happen for 5.6)

**Comment by rsmontero** [comment] 2019-02-04 14:02
Closing this one, 5.8 includes also virtual network templates; that adds more flexibility to the user-controlled address space mentioned previously.

**Closed by rsmontero** 2019-02-04 14:02 UTC
Labels: Category: CLI, Category: Core & System, Community, Status: Pending, Type: Bug
