### ISSUE TITLE
DEFAULT_IMAGE_PERSISTENT stopped working

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3781] opened 2019-09-27 16:52 UTC
**Description**
Hi, I have strange issue when DEFAULT_IMAGE_PERSISTENT is stopped working.

In the group both parameters are set to:
```
OPENNEBULA=[
  DEFAULT_IMAGE_PERSISTENT="YES",
  DEFAULT_IMAGE_PERSISTENT_NEW="YES" ]
```

Creating new image, setting it to persistent, but creating new VM from the template still instantiates VM with non persistent drive

**To Reproduce**
I have this behavior on my server. I don't know the way to reproduce it.

**Expected behavior**
New VM are always instantiated with persistent drive

**Details**
 - Affected Component: oned
 - Hypervisor: kvm
 - Version: 5.8.4

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by tinova** [comment] 2020-02-26 17:41
does this happen on 5.10 also? closing until further feedback as we couldn't reproduce

**Closed by tinova** 2020-02-26 17:41 UTC

**Comment by kvaps** [comment] 2020-02-27 13:55
Yes 5.10.2 having the same problem,

user:
```xml
<USER>
  <ID>86</ID>
  <GID>177</GID>
  <GROUPS>
    <ID>177</ID>
  </GROUPS>
  <GNAME>ov177</GNAME>
  <NAME>ov177</NAME>
  <PASSWORD><![CDATA[9e4e36e296df64c4ccd5d5a9560c88b95bbfe24b3461667c30d1af781a3245e9]]></PASSWORD>
  <AUTH_DRIVER><![CDATA[core]]></AUTH_DRIVER>
  <ENABLED>1</ENABLED>
  <TEMPLATE>
    <SUNSTONE>
      <DEFAULT_VIEW><![CDATA[cloud]]></DEFAULT_VIEW>
    </SUNSTONE>
    <TOKEN_PASSWORD><![CDATA[05fc4e8ba0e5e1684e7873f4cb8e41e69f156db1f57158c09132496892fd37a0]]></TOKEN_PASSWORD>
  </TEMPLATE>
  <DATASTORE_QUOTA>
    <DATASTORE>
      <ID><![CDATA[106]]></ID>
      <IMAGES><![CDATA[-1]]></IMAGES>
      <IMAGES_USED><![CDATA[1]]></IMAGES_USED>
      <SIZE><![CDATA[-1]]></SIZE>
      <SIZE_USED><![CDATA[2048]]></SIZE_USED>
    </DATASTORE>
  </DATASTORE_QUOTA>
  <NETWORK_QUOTA>
    <NETWORK>
      <ID><![CDATA[0]]></ID>
      <LEASES><![CDATA[-1]]></LEASES>
      <LEASES_USED><![CDATA[1]]></LEASES_USED>
    </NETWORK>
  </NETWORK_QUOTA>
  <VM_QUOTA>
    <VM>
      <CPU><![CDATA[-1]]></CPU>
      <CPU_USED><![CDATA[0.50]]></CPU_USED>
      <MEMORY><![CDATA[-1]]></MEMORY>
      <MEMORY_USED><![CDATA[512]]></MEMORY_USED>
      <RUNNING_CPU><![CDATA[-1]]></RUNNING_CPU>
      <RUNNING_CPU_USED><![CDATA[-1]]></RUNNING_CPU_USED>
      <RUNNING_MEMORY><![CDATA[-1]]></RUNNING_MEMORY>
      <RUNNING_MEMORY_USED><![CDATA[-1024]]></RUNNING_MEMORY_USED>
      <RUNNING_VMS><![CDATA[-1]]></RUNNING_VMS>
      <RUNNING_VMS_USED><![CDATA[-2]]></RUNNING_VMS_USED>
      <SYSTEM_DISK_SIZE><![CDATA[-1]]></SYSTEM_DISK_SIZE>
      <SYSTEM_DISK_SIZE_USED><![CDATA[3072]]></SYSTEM_DISK_SIZE_USED>
      <VMS><![CDATA[-1]]></VMS>
      <VMS_USED><![CDATA[1]]></VMS_USED>
    </VM>
  </VM_QUOTA>
  <IMAGE_QUOTA>
    <IMAGE>
      <ID><![CDATA[209]]></ID>
      <RVMS><![CDATA[-1]]></RVMS>
      <RVMS_USED><![CDATA[1]]></RVMS_USED>
    </IMAGE>
  </IMAGE_QUOTA>
  <DEFAULT_USER_QUOTAS>
    <DATASTORE_QUOTA/>
    <NETWORK_QUOTA/>
    <VM_QUOTA/>
    <IMAGE_QUOTA/>
  </DEFAULT_USER_QUOTAS>
</USER>
```

group:

```xml
<GROUP>
  <ID>177</ID>
  <NAME>ov177</NAME>
  <TEMPLATE>
    <OPENNEBULA>
      <DEFAULT_IMAGE_PERSISTENT><![CDATA[YES]]></DEFAULT_IMAGE_PERSISTENT>
      <DEFAULT_IMAGE_PERSISTENT_NEW><![CDATA[YES]]></DEFAULT_IMAGE_PERSISTENT_NEW>
    </OPENNEBULA>
    <SUNSTONE>
      <DEFAULT_VIEW><![CDATA[]]></DEFAULT_VIEW>
      <VIEWS><![CDATA[admin]]></VIEWS>
    </SUNSTONE>
  </TEMPLATE>
  <USERS>
    <ID>86</ID>
  </USERS>
  <ADMINS/>
  <DATASTORE_QUOTA>
    <DATASTORE>
      <ID><![CDATA[106]]></ID>
      <IMAGES><![CDATA[-2]]></IMAGES>
      <IMAGES_USED><![CDATA[1]]></IMAGES_USED>
      <SIZE><![CDATA[10240]]></SIZE>
      <SIZE_USED><![CDATA[2048]]></SIZE_USED>
    </DATASTORE>
  </DATASTORE_QUOTA>
  <NETWORK_QUOTA>
    <NETWORK>
      <ID><![CDATA[0]]></ID>
      <LEASES><![CDATA[1]]></LEASES>
      <LEASES_USED><![CDATA[1]]></LEASES_USED>
    </NETWORK>
  </NETWORK_QUOTA>
  <VM_QUOTA>
    <VM>
      <CPU><![CDATA[6.01]]></CPU>
      <CPU_USED><![CDATA[0.50]]></CPU_USED>
      <MEMORY><![CDATA[16384]]></MEMORY>
      <MEMORY_USED><![CDATA[512]]></MEMORY_USED>
      <RUNNING_CPU><![CDATA[-1]]></RUNNING_CPU>
      <RUNNING_CPU_USED><![CDATA[-1]]></RUNNING_CPU_USED>
      <RUNNING_MEMORY><![CDATA[-1]]></RUNNING_MEMORY>
      <RUNNING_MEMORY_USED><![CDATA[-1024]]></RUNNING_MEMORY_USED>
      <RUNNING_VMS><![CDATA[-1]]></RUNNING_VMS>
      <RUNNING_VMS_USED><![CDATA[-2]]></RUNNING_VMS_USED>
      <SYSTEM_DISK_SIZE><![CDATA[-2]]></SYSTEM_DISK_SIZE>
      <SYSTEM_DISK_SIZE_USED><![CDATA[3072]]></SYSTEM_DISK_SIZE_USED>
      <VMS><![CDATA[-2]]></VMS>
      <VMS_USED><![CDATA[1]]></VMS_USED>
    </VM>
  </VM_QUOTA>
  <IMAGE_QUOTA>
    <IMAGE>
      <ID><![CDATA[209]]></ID>
      <RVMS><![CDATA[-1]]></RVMS>
      <RVMS_USED><![CDATA[1]]></RVMS_USED>
    </IMAGE>
  </IMAGE_QUOTA>
  <DEFAULT_GROUP_QUOTAS>
    <DATASTORE_QUOTA>
      <DATASTORE>
        <ID><![CDATA[2]]></ID>
        <IMAGES><![CDATA[0]]></IMAGES>
        <IMAGES_USED><![CDATA[0]]></IMAGES_USED>
        <SIZE><![CDATA[0]]></SIZE>
        <SIZE_USED><![CDATA[0]]></SIZE_USED>
      </DATASTORE>
    </DATASTORE_QUOTA>
    <NETWORK_QUOTA>
      <NETWORK>
        <ID><![CDATA[23]]></ID>
        <LEASES><![CDATA[0]]></LEASES>
        <LEASES_USED><![CDATA[0]]></LEASES_USED>
      </NETWORK>
      <NETWORK>
        <ID><![CDATA[3]]></ID>
        <LEASES><![CDATA[0]]></LEASES>
        <LEASES_USED><![CDATA[0]]></LEASES_USED>
      </NETWORK>
    </NETWORK_QUOTA>
    <VM_QUOTA>
      <VM>
        <CPU><![CDATA[0]]></CPU>
        <CPU_USED><![CDATA[0]]></CPU_USED>
        <MEMORY><![CDATA[0]]></MEMORY>
        <MEMORY_USED><![CDATA[0]]></MEMORY_USED>
        <RUNNING_CPU><![CDATA[-2]]></RUNNING_CPU>
        <RUNNING_CPU_USED><![CDATA[0]]></RUNNING_CPU_USED>
        <RUNNING_MEMORY><![CDATA[-2]]></RUNNING_MEMORY>
        <RUNNING_MEMORY_USED><![CDATA[0]]></RUNNING_MEMORY_USED>
        <RUNNING_VMS><![CDATA[-2]]></RUNNING_VMS>
        <RUNNING_VMS_USED><![CDATA[0]]></RUNNING_VMS_USED>
        <SYSTEM_DISK_SIZE><![CDATA[0]]></SYSTEM_DISK_SIZE>
        <SYSTEM_DISK_SIZE_USED><![CDATA[0]]></SYSTEM_DISK_SIZE_USED>
        <VMS><![CDATA[0]]></VMS>
        <VMS_USED><![CDATA[0]]></VMS_USED>
      </VM>
    </VM_QUOTA>
    <IMAGE_QUOTA/>
  </DEFAULT_GROUP_QUOTAS>
</GROUP>
```

template:
```xml
<VMTEMPLATE>
  <ID>94</ID>
  <UID>0</UID>
  <GID>0</GID>
  <UNAME>oneadmin</UNAME>
  <GNAME>oneadmin</GNAME>
  <NAME>openSUSE Leap 15</NAME>
  <PERMISSIONS>
    <OWNER_U>1</OWNER_U>
    <OWNER_M>1</OWNER_M>
    <OWNER_A>0</OWNER_A>
    <GROUP_U>0</GROUP_U>
    <GROUP_M>0</GROUP_M>
    <GROUP_A>0</GROUP_A>
    <OTHER_U>1</OTHER_U>
    <OTHER_M>0</OTHER_M>
    <OTHER_A>0</OTHER_A>
  </PERMISSIONS>
  <REGTIME>1566391082</REGTIME>
  <TEMPLATE>
    <CONTEXT>
      <NETWORK><![CDATA[YES]]></NETWORK>
      <PASSWORD_RESET><![CDATA[NO]]></PASSWORD_RESET>
      <REPORT_READY><![CDATA[YES]]></REPORT_READY>
      <SSH_PUBLIC_KEY><![CDATA[$USER[SSH_PUBLIC_KEY]]]></SSH_PUBLIC_KEY>
      <TOKEN><![CDATA[YES]]></TOKEN>
    </CONTEXT>
    <CPU><![CDATA[0.5]]></CPU>
    <DISK>
      <IMAGE><![CDATA[openSUSE Leap 15 [5.8.0-1.20190701]]]></IMAGE>
      <IMAGE_UNAME><![CDATA[oneadmin]]></IMAGE_UNAME>
      <SIZE><![CDATA[3072]]></SIZE>
    </DISK>
    <GRAPHICS>
      <LISTEN><![CDATA[0.0.0.0]]></LISTEN>
      <RANDOM_PASSWD><![CDATA[YES]]></RANDOM_PASSWD>
      <TYPE><![CDATA[VNC]]></TYPE>
    </GRAPHICS>
    <INPUTS_ORDER><![CDATA[]]></INPUTS_ORDER>
    <LABELS><![CDATA[Cloud]]></LABELS>
    <LOGO><![CDATA[images/logos/opensuse.png]]></LOGO>
    <MEMORY><![CDATA[512]]></MEMORY>
    <MEMORY_UNIT_COST><![CDATA[MB]]></MEMORY_UNIT_COST>
    <NIC_DEFAULT>
      <MODEL><![CDATA[virtio]]></MODEL>
    </NIC_DEFAULT>
    <OS>
      <ARCH><![CDATA[x86_64]]></ARCH>
      <BOOT><![CDATA[]]></BOOT>
    </OS>
    <VCPU><![CDATA[1]]></VCPU>
  </TEMPLATE>
</VMTEMPLATE>
```
image:
```xml
<IMAGE>
  <ID>212</ID>
  <UID>0</UID>
  <GID>0</GID>
  <UNAME>oneadmin</UNAME>
  <GNAME>oneadmin</GNAME>
  <NAME>openSUSE Leap 15 [5.8.0-1.20190701]</NAME>
  <PERMISSIONS>
    <OWNER_U>1</OWNER_U>
    <OWNER_M>1</OWNER_M>
    <OWNER_A>0</OWNER_A>
    <GROUP_U>1</GROUP_U>
    <GROUP_M>0</GROUP_M>
    <GROUP_A>0</GROUP_A>
    <OTHER_U>1</OTHER_U>
    <OTHER_M>0</OTHER_M>
    <OTHER_A>0</OTHER_A>
  </PERMISSIONS>
  <TYPE>0</TYPE>
  <DISK_TYPE>2</DISK_TYPE>
  <PERSISTENT>0</PERSISTENT>
  <REGTIME>1571652184</REGTIME>
  <SOURCE><![CDATA[/dev/drbd/by-res/one-image-212/0]]></SOURCE>
  <PATH><![CDATA[https://marketplace.opennebula.wedos.cloud/images/opensuse-leap-15.qcow2]]></PATH>
  <FSTYPE><![CDATA[]]></FSTYPE>
  <SIZE>2048</SIZE>
  <STATE>2</STATE>
  <RUNNING_VMS>1</RUNNING_VMS>
  <CLONING_OPS>0</CLONING_OPS>
  <CLONING_ID>-1</CLONING_ID>
  <TARGET_SNAPSHOT>-1</TARGET_SNAPSHOT>
  <DATASTORE_ID>106</DATASTORE_ID>
  <DATASTORE>cloud-images</DATASTORE>
  <VMS>
    <ID>358</ID>
  </VMS>
  <CLONES/>
  <APP_CLONES/>
  <TEMPLATE>
    <DEV_PREFIX><![CDATA[vd]]></DEV_PREFIX>
    <FORMAT><![CDATA[raw]]></FORMAT>
    <LABELS><![CDATA[OS]]></LABELS>
  </TEMPLATE>
  <SNAPSHOTS>
    <ALLOW_ORPHANS><![CDATA[NO]]></ALLOW_ORPHANS>
    <CURRENT_BASE><![CDATA[-1]]></CURRENT_BASE>
    <NEXT_SNAPSHOT><![CDATA[0]]></NEXT_SNAPSHOT>
  </SNAPSHOTS>
</IMAGE>
```

Instantiated VM:

```xml
<VM>
  <ID>419</ID>
  <UID>86</UID>
  <GID>177</GID>
  <UNAME>ov177</UNAME>
  <GNAME>ov177</GNAME>
  <NAME>openSUSE Leap 15-419</NAME>
  <PERMISSIONS>
    <OWNER_U>1</OWNER_U>
    <OWNER_M>1</OWNER_M>
    <OWNER_A>0</OWNER_A>
    <GROUP_U>0</GROUP_U>
    <GROUP_M>0</GROUP_M>
    <GROUP_A>0</GROUP_A>
    <OTHER_U>0</OTHER_U>
    <OTHER_M>0</OTHER_M>
    <OTHER_A>0</OTHER_A>
  </PERMISSIONS>
  <LAST_POLL>0</LAST_POLL>
  <STATE>1</STATE>
  <LCM_STATE>0</LCM_STATE>
  <PREV_STATE>1</PREV_STATE>
  <PREV_LCM_STATE>0</PREV_LCM_STATE>
  <RESCHED>0</RESCHED>
  <STIME>1582811620</STIME>
  <ETIME>0</ETIME>
  <DEPLOY_ID/>
  <MONITORING/>
  <TEMPLATE>
    <AUTOMATIC_DS_REQUIREMENTS><![CDATA[("CLUSTERS/ID" @> 0 | "CLUSTERS/ID" @> 100)]]></AUTOMATIC_DS_REQUIREMENTS>
    <AUTOMATIC_NIC_REQUIREMENTS><![CDATA[("CLUSTERS/ID" @> 0 | "CLUSTERS/ID" @> 100)]]></AUTOMATIC_NIC_REQUIREMENTS>
    <AUTOMATIC_REQUIREMENTS><![CDATA[(CLUSTER_ID = 0 | CLUSTER_ID = 100) & !(PUBLIC_CLOUD = YES) & !(PIN_POLICY = PINNED)]]></AUTOMATIC_REQUIREMENTS>
    <CONTEXT>
      <DISK_ID><![CDATA[1]]></DISK_ID>
      <NETWORK><![CDATA[YES]]></NETWORK>
      <ONEGATE_ENDPOINT><![CDATA[https://gate.opennebula.stage.wedos.cloud]]></ONEGATE_ENDPOINT>
      <PASSWORD_RESET><![CDATA[NO]]></PASSWORD_RESET>
      <REPORT_READY><![CDATA[YES]]></REPORT_READY>
      <SSH_PUBLIC_KEY><![CDATA[]]></SSH_PUBLIC_KEY>
      <TARGET><![CDATA[hda]]></TARGET>
      <TOKEN><![CDATA[YES]]></TOKEN>
      <VMID><![CDATA[419]]></VMID>
    </CONTEXT>
    <CPU><![CDATA[0.5]]></CPU>
    <CREATED_BY><![CDATA[86]]></CREATED_BY>
    <DISK>
      <ALLOW_ORPHANS><![CDATA[yes]]></ALLOW_ORPHANS>
      <CLONE><![CDATA[YES]]></CLONE>
      <CLONE_TARGET><![CDATA[SYSTEM]]></CLONE_TARGET>
      <CLUSTER_ID><![CDATA[0,100]]></CLUSTER_ID>
      <DATASTORE><![CDATA[cloud-images]]></DATASTORE>
      <DATASTORE_ID><![CDATA[106]]></DATASTORE_ID>
      <DEV_PREFIX><![CDATA[vd]]></DEV_PREFIX>
      <DISK_ID><![CDATA[0]]></DISK_ID>
      <DISK_SNAPSHOT_TOTAL_SIZE><![CDATA[0]]></DISK_SNAPSHOT_TOTAL_SIZE>
      <DISK_TYPE><![CDATA[BLOCK]]></DISK_TYPE>
      <DRIVER><![CDATA[raw]]></DRIVER>
      <IMAGE><![CDATA[openSUSE Leap 15 [5.8.0-1.20190701]]]></IMAGE>
      <IMAGE_ID><![CDATA[212]]></IMAGE_ID>
      <IMAGE_STATE><![CDATA[2]]></IMAGE_STATE>
      <IMAGE_UNAME><![CDATA[oneadmin]]></IMAGE_UNAME>
      <LN_TARGET><![CDATA[NONE]]></LN_TARGET>
      <ORIGINAL_SIZE><![CDATA[2048]]></ORIGINAL_SIZE>
      <READONLY><![CDATA[NO]]></READONLY>
      <SAVE><![CDATA[NO]]></SAVE>
      <SIZE><![CDATA[3072]]></SIZE>
      <SOURCE><![CDATA[/dev/drbd/by-res/one-image-212/0]]></SOURCE>
      <TARGET><![CDATA[vda]]></TARGET>
      <TM_MAD><![CDATA[linstor_un]]></TM_MAD>
      <TYPE><![CDATA[BLOCK]]></TYPE>
    </DISK>
    <GRAPHICS>
      <LISTEN><![CDATA[0.0.0.0]]></LISTEN>
      <PASSWD><![CDATA[46c5a40c8607b367f22ed383b7052dde37840f8d8f62e045ca557d1ea7447748]]></PASSWD>
      <RANDOM_PASSWD><![CDATA[YES]]></RANDOM_PASSWD>
      <TYPE><![CDATA[VNC]]></TYPE>
    </GRAPHICS>
    <MEMORY><![CDATA[512]]></MEMORY>
    <NIC_DEFAULT>
      <MODEL><![CDATA[virtio]]></MODEL>
    </NIC_DEFAULT>
    <OS>
      <ARCH><![CDATA[x86_64]]></ARCH>
      <BOOT><![CDATA[]]></BOOT>
    </OS>
    <TEMPLATE_ID><![CDATA[94]]></TEMPLATE_ID>
    <VCPU><![CDATA[1]]></VCPU>
    <VMID><![CDATA[419]]></VMID>
  </TEMPLATE>
  <USER_TEMPLATE>
    <INPUTS_ORDER><![CDATA[]]></INPUTS_ORDER>
    <LABELS><![CDATA[Cloud]]></LABELS>
    <LOGO><![CDATA[images/logos/opensuse.png]]></LOGO>
    <MEMORY_UNIT_COST><![CDATA[MB]]></MEMORY_UNIT_COST>
  </USER_TEMPLATE>
  <HISTORY_RECORDS/>
</VM>
```

**Comment by kvaps** [comment] 2020-02-27 13:57
That's not working with both: `IMAGE`+`IMAGE_UNAME` and `IMAGE_ID`

**Comment by kvaps** [comment] 2020-02-28 15:11
My bad, my meaning about this function was wrong. 

I was thinking that it will enable `Instantiate template as persistent`  feature, but it is just sets `PERSISTENT=yes` for newly created images by default.
