### ISSUE TITLE
Can not use resize --cpu 1.67 if quota set

### ISSUE THREAD

**Issue by OpenNebulaProject** [OpenNebula/one#1421] opened 2017-11-20 12:13 UTC
---

Author Name: **kvaps kvaps** (kvaps kvaps)
Original Redmine Issue: 5491, https://dev.opennebula.org/issues/5491
Original Date: 2017-10-23

---

Hi, I have quota for group:

```
VM=[
  CPU="1.67",
  MEMORY="1024",
  SYSTEM_DISK_SIZE="10240",
  VMS="1", ]

```

Now when I run

 onevm resize --cpu 1.67 --vcpu 5 <vmid>

I see this error:

[one.vm.resize] User [0] : group [<group_id>] limit of 1.67 reached for CPU quota in VM.

but:

 onevm resize --cpu 1.66 --vcpu 5 <vmid>

is working fine

**Comment by juanmont** [comment] 2017-12-01 15:40
So this seems to be the expected behavior, closing... Will reopen if needed

**Closed by juanmont** 2017-12-01 15:40 UTC
Labels: Category: Core & System, Community, Status: Pending, Type: Bug

**Comment by kvaps** [comment] 2017-12-02 12:09
@juanmont, where `0.01` is gone? :)
Not expected behavor, exactly.
If you set another quota it will work, but not with `1.67` value

**Comment by rsmontero** [comment] 2017-12-04 16:07
Sorry, we still do not get the issue. You set quota 1.67, so you are able to use 1.66 but not 1.67. Is that what you are saying?

**Comment by kvaps** [comment] 2017-12-04 16:14
Hello @rsmontero.
Yes it's true
* Set quota to `1.65` + create vm with `1.65` cpu = working
* Set quota to `1.66` + create vm with `1.66` cpu = working
* Set quota to `1.67` + create vm with `1.67` cpu = quota error

**Comment by rsmontero** [comment] 2017-12-04 17:00
Yes it is the expected behavior, it is checked with the limit with <=

https://github.com/OpenNebula/one/blob/master/src/um/Quota.cc#L233

**Comment by kvaps** [comment] 2017-12-04 17:04
but `1.67` and `1.67` this is same value, and it's not work

**Comment by kvaps** [comment] 2018-02-20 09:51
This bug still present:

*Steps for reproduse:*

* Create group A
* Set quota "CPU=1.67" for group A
* Create VM in group A with "CPU=1.67"

You will recieve this error:
```
[one.vm.resize] User [305] : group [242] limit of 1.67 reached for CPU quota in VM.
```
