### ISSUE TITLE
Error in opennebula cloud

### ISSUE THREAD

**Issue by nrsnrs** [OpenNebula/one#2235] opened 2018-06-29 09:35 UTC
PLZ help me sir....

Fri Jun 29 09:26:52 2018 [Z0][VM][I]: New state is ACTIVE
Fri Jun 29 09:26:52 2018 [Z0][VM][I]: New LCM state is PROLOG
Fri Jun 29 09:26:55 2018 [Z0][TM][I]: Command execution fail: /var/lib/one/remotes/tm/ssh/clone ditcore.com:/var/lib/one/datastores/1/c4cf85d3728a0bfe4b3fa8622a362b60 88.198.130.129:/var/lib/one/datastores/0/2/disk.0 2 1
Fri Jun 29 09:26:55 2018 [Z0][TM][I]: clone: Cloning ditcore.com:/var/lib/one/datastores/1/c4cf85d3728a0bfe4b3fa8622a362b60 in /var/lib/one/datastores/0/2/disk.0
Fri Jun 29 09:26:55 2018 [Z0][TM][E]: clone: Command "scp -r ditcore.com:/var/lib/one/datastores/1/c4cf85d3728a0bfe4b3fa8622a362b60 88.198.130.129:/var/lib/one/datastores/0/2/disk.0" failed: Host key verification failed.
Fri Jun 29 09:26:55 2018 [Z0][TM][E]: Error copying ditcore.com:/var/lib/one/datastores/1/c4cf85d3728a0bfe4b3fa8622a362b60 to 88.198.130.129:/var/lib/one/datastores/0/2/disk.0
Fri Jun 29 09:26:55 2018 [Z0][TM][I]: ExitCode: 1
Fri Jun 29 09:26:55 2018 [Z0][TM][E]: Error executing image transfer script: Error copying ditcore.com:/var/lib/one/datastores/1/c4cf85d3728a0bfe4b3fa8622a362b60 to 88.198.130.129:/var/lib/one/datastores/0/2/disk.0
Fri Jun 29 09:26:55 2018 [Z0][VM][I]: New LCM state is PROLOG_FAILURE

**Comment by nrsnrs** [comment] 2018-06-29 09:36
plz help to start the vm in opennebula

**Comment by dann1** [comment] 2018-06-29 09:47
Seems you are having issues with the ssh configuration, read carefully [passwordless ssh configuration](http://docs.opennebula.org/5.4/deployment/node_installation/kvm_node_installation.html#step-4-configure-passwordless-ssh). Try to ssh as oneadmin from the frontend to the node, it shouldn't ask for key nor password. Your VM log suggests oneadmin user in the node doesn't have the oneadmin user frontend key.

**Comment by nrsnrs** [comment] 2018-06-29 09:54
dear sir,, i have run all ssh commands..

**Comment by dann1** [comment] 2018-06-29 09:57
Close this issue and open an entry in https://forum.opennebula.org/, as this is not a bug or feature and follow the discussion there. You'll get more attention from people.

**Comment by nrsnrs** [comment] 2018-06-29 10:00
plz give me a proper doc of opennebula

**Comment by dann1** [comment] 2018-06-29 10:07
http://docs.opennebula.org/5.4/. I'm closing this since it's not an issue, but a human error :)

**Closed by dann1** 2018-06-29 10:07 UTC
