### ISSUE TITLE
Version 6.4 cannot upload image files

### ISSUE THREAD

**Issue by wangwei0537** [OpenNebula/one#6047] opened 2022-12-14 11:22 UTC
**Description**
Version 6.4 cannot upload image files, whether through https or local upload

**Details**
 - Affected Component: Sunstone, Scheduler  Storage
 - Hypervisor:  KVM
 - Version: 6.4

**Additional context**
When I execute the following command：
 $oneimage create --datastore cephds --name worker --type OS --persistent  --path /home/kvm/testvm2.qcow2  --size 61440 --description "Semantic engine worker system image"
the result is：
[one.image.allocate] Cannot parse image SIZE: Failed to get image head
same below：
$oneimage create --datastore cephds --name worker --type OS --persistent  --path /image.img --description "Semantic engine worker system image"
[one.image.allocate] Error allocating a new image.

**Comment by atodorov-storpool** [comment] 2022-12-14 12:29
Hello,
Long shot - did you try from the listed SAFE_DIRS for the datastore? 
try placing the file in /var/tmp/image.img and use the path from there.

**Comment by wangwei0537** [comment] 2022-12-14 13:06
Hello, I just tried to put the image file image.img in the /var/tmp directory and execute the same command:
oneimage create --datastore cephds --name worker --type OS --persistent --path /var/tmp/image.img --description "Semantic engine worker system image"
It is still the following error:
[one.image.allocate] Error allocating a new image.

![image](https://user-images.githubusercontent.com/7962425/207602554-98228e62-faae-4c92-a9e6-0f0187ad56b0.png)

**Comment by rsmontero** [comment] 2022-12-14 13:11
Could you check /var/log/one/oned.log file for related error messages?

**Comment by wangwei0537** [comment] 2022-12-14 13:23
The log has a sql syntax error, as follows:

![image](https://user-images.githubusercontent.com/7962425/207606304-e79081a4-7f37-4915-9d13-c413e4e1ebc8.png)

![image](https://user-images.githubusercontent.com/7962425/207606550-7d7fe5c6-5812-4bb4-ab85-83734d328ed0.png)

Is the database version required?

**Comment by xorel** [comment] 2023-01-31 07:45
What OS and version do you use?

**Comment by xorel** [comment] 2023-01-31 08:04
Also, is this a fresh install or some upgrade?
Can you also run `onedb version` and put it here?

**Comment by xorel** [comment] 2023-02-08 16:38
I could not reproduce the issue. Closing now.
If you can provide us with more details or reproduce, we can re-open.

**Closed by xorel** 2023-02-08 16:38 UTC
Labels: Status: Pending, Community, Category: Drivers - Storage, Type: Bug, Priority: Normal
