### ISSUE TITLE
LVM datastore migration does not work

### ISSUE THREAD

**Issue by kvaps** [OpenNebula/one#3130] opened 2019-03-26 10:52 UTC
**Description**

Here is specific check for that

https://github.com/OpenNebula/one/blob/release-5.8.0/src/tm_mad/fs_lvm/mv#L86-L88

```bash
if [ "${TYPE}" != "BLOCK" ]; then
    exit 0
fi
```

But disk type is always
```
TYPE = "FILE"
```

**To Reproduce**
* Configure lvm datastore according the [documentation](docs.opennebula.org/5.8/deployment/open_cloud_storage_setup/lvm_drivers.html)
* Instantiate new VM
* Shutdown it, and try to migrate datastore

**Expected behavior**
VM will be migrated with all data

**Actual behavior**
Only metadata directory will be moved, VM will continue use logical volume from the old datastore

**Details**
 - Affected Component: Storage drivers
 - Hypervisor: KVM
 - Version: 5.6 5.8

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by kvaps** [comment] 2019-03-26 11:23
There is more detailed discussion about this issue:
https://forum.opennebula.org/t/why-images-ds-parameters-affects-system-ds/7072

**Comment by rsmontero** [comment] 2019-03-26 14:53
Closing as duplicate of #2359

**Closed by rsmontero** 2019-03-26 14:53 UTC
Labels: Category: Drivers - Storage, Community, Priority: Normal, Status: Accepted, Type: Bug
