### ISSUE TITLE
No Labels shown for Custom Attributes specified in service template when description is empty

### ISSUE THREAD

**Issue by parodotdev** [OpenNebula/one#1579] opened 2017-12-12 18:24 UTC
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [x] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [x] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description
After specifying a few _User Input_ fields under the context section in the template of the VM. During instantiation these fields are shown under _Custom Attributes_ without any label. User has no way of knowing what the fields expects. This only happens when description is empty.

### Expected Behavior
The fields shown in the Custom Attributes section during VM instantiation should have Names as labels when description is empty
### Actual Behavior
The fields are shown in the Custom Attributes section during VM instantiation without any Labels
## How to reproduce

Click on the VMs under Templates
Choose Context in the Update VM Template view
Under the User Input Input section
Add an entry
Key in the Name
Leave the description blank
Click Update
Now Choose Instantiate

The instantiate screen has the custom attributes section with field and no label

# Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by abelCoronado93** [comment] 2017-12-13 11:45
Hello @parodotdev,

It's not a bug. 'Name' is the name that OpenNebula assign to the internal variable of the user input and 'Description' is the label that the end user sees.

Regards.

**Closed by abelCoronado93** 2017-12-13 11:45 UTC
Labels: Category: Sunstone, Community, Status: Pending, Type: Bug
