### ISSUE TITLE
Race condition when deleting scheduled actions

### ISSUE THREAD

**Issue by Yenya** [OpenNebula/one#5289] opened 2021-03-09 16:10 UTC
Originally discussed here:
https://forum.opennebula.io/t/scheduled-actions-sysadmin-netadmin-course-in-one/9264/5

**Description**
When deleting a scheduled action for a VM, it sometimes does not get deleted even though `onevm delete-chart $vmid $n` reports no error. From my shell, with VM 4308 which had five scheduled actions:

```
#  onevm delete-chart 4308 0
#  onevm delete-chart 4308 2
#  onevm delete-chart 4308 3
#  onevm delete-chart 4308 1
#  onevm delete-chart 4308 4
#  onevm delete-chart 4308 0
Sched action 0 not found
#  onevm delete-chart 4308 1         ... what? Action 1 has been deleted above
#  onevm delete-chart 4308 2
Sched action 2 not found
#  onevm delete-chart 4308 3
Sched action 3 not found
#  onevm delete-chart 4308 4         ... also should be deleted above, but still reports no error
#  onevm delete-chart 4308 4
Sched action 4 not found
```

**To Reproduce**
Create a VM with some periodic actions (I wanted to do daily shutdown [poweroff-hard] and after that revert to the "gold standard" snapshot, not that it does matter for this problem).

Run `onevm delete-chart` for these actions repeatedly. Sometimes the action reappears few seconds later after it has been successfully deleted (i.e. `onevm delete-chart` finished with no error printed).

**Expected behavior**
The scheduled action should be deleted when `onevm delete-chart` reports no error.

**Details**
 - Affected Component: oned
 - Hypervisor: KVM
 - Version: 5.12.0.3 CE, CentOS 7, MySQL DB Backend.
 - 
**Additional context**
I have about 400 such VMs, which used to have up to three scheduled actions each, I wanted to delete all these actions, so I ran something like this:

```
for vmid in `seq $first $last`
do
   for action_id in `seq 0 2`
   do
       onevm delete-chart $vmid $action_id
   done
done
```
A day later after running the above, I discovered at least 100 out of 400 VMs still have at least one scheduled action present.

I turned on MySQL query debugging for the above case (VM 4308 and sched_action with ID 4), and it seems that the same MySQL client (supposedly oned), at one occasion did `UPDATE vm_pool SET body = (body without sched_id 4)` only to do `UPDATE vm_pool SET body = (body with sched_id 4)`  few seconds later.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [ ] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by al3xhh** [comment] 2021-03-10 09:23
Hello @Yenya,

First of all, thank you for testing the feature. I have done some tests, but I'm not able to reproduce your issue:

1. Create the charts:

```
$ onevm create-chart 0
VM 0: suspend scheduled at +1209600
VM 0: terminate scheduled at +2419200
```

```
$ onevm show 0        
VIRTUAL MACHINE 0 INFORMATION                                                   
ID                  : 0                   
NAME                : test                
USER                : oneadmin            
GROUP               : oneadmin            
STATE               : ACTIVE              
LCM_STATE           : RUNNING             
LOCK                : None                
RESCHED             : No                  
HOST                : localhost           
CLUSTER ID          : 0                   
CLUSTER             : default             
START TIME          : 03/10 09:58:52      
END TIME            : -                   
DEPLOY ID           : 3a625980-270d-4465-8c52-4ba125ac44d1

VIRTUAL MACHINE MONITORING                                                      
CPU                 : 0.0                 
MEMORY              : 35.7M               
NETTX               : 0K                  
NETRX               : 0K                  
DISKRDBYTES         : 0                   
DISKRDIOPS          : 0                   
DISKWRBYTES         : 0                   
DISKWRIOPS          : 0                   
ID                  : 0                   
TIMESTAMP           : 1615366950          

PERMISSIONS                                                                     
OWNER               : um-                 
GROUP               : ---                 
OTHER               : ---                 

VIRTUAL MACHINE HISTORY                                                         
SEQ UID  REQ   HOST         ACTION       DS           START        TIME     PROLOG
  0 -    -     localhost    none          0  03/10 09:59:05   0d 00h04m   0h00m00s

SCHEDULED ACTIONS                                                               
   ID    ACTION  ARGS   SCHEDULED REPEAT   END  DONE                             MESSAGE CHARTER        
    0   suspend     - 01/15 01:00                 -                                   - In 14.0 days
    1 terminate     - 01/29 01:00                 -                                   - In 28.0 days

VIRTUAL MACHINE TEMPLATE                                                        
AUTOMATIC_REQUIREMENTS="!(PUBLIC_CLOUD = YES) & !(PIN_POLICY = PINNED)"
CPU="1"
MEMORY="1"
OS=[
  UUID="3a625980-270d-4465-8c52-4ba125ac44d1" ]
TM_MAD_SYSTEM="ssh"
VMID="0"
```

2. Delete both sched actions:

```
$ onevm delete-chart 0 0
$ onevm delete-chart 0 1
```

3. Try to delete them again:

```
$ onevm delete-chart 0 0
Sched action 0 not found

$ onevm delete-chart 0 0
Sched action 0 not found

$ onevm delete-chart 0 0
Sched action 0 not found

$ onevm delete-chart 0 1
Sched action 1 not found

$ onevm delete-chart 0 1
Sched action 1 not found

$ onevm delete-chart 0 1
Sched action 1 not found
```

4. Try to delete it 1000 times with some ruby script:

```
count = 0

1000.times do
    ret = system('onevm delete-chart 0 0 2> /dev/null')

    if ret
        puts 'WORKED!'
    else
        count +=1
    end
end

puts "It worked #{1000 - count} times and it didn't work #{count} times"

$ ruby test.rb 
It worked 0 times and it didn't work 1000 times
```

Could you please provide more information about the VMs and your deployment?

Best,
Álex.

**Comment by Yenya** [comment] 2021-03-10 10:59
Álex: as I wrote above, the problem manifests itself in about 5 to 10 % of cases - I started with 400 VMs and three scheduled actions for each of them, the first run deleted all the actions except 140, the second one all except 10.

So I guess in your test it managed to delete both actions on the first try. You either need more VMs, or you need to add a new scheduled action, if the previous one is reported as deleted with three or four consecutive retries.

Also, do you use MySQL backend?

**Comment by Yenya** [comment] 2021-03-10 17:14
CentOS 7.

I have pretty-printed the XMLs in the `body` column of`UPDATE vm_pool SET ...` statements from my MySQL log, and ran `diff -u` on them. The bodies indeed differ in the`<SCHED_ACTION>` sections. The key ones are these:

* UPDATE #5 removes the SCHED_ACTION with ID=3
* UPDATE #6 removes ID=1
* UPDATE #7 removes ID=4
* UPDATE #8 inserts ID=1 and ID=4 back
* UPDATE #9 removes ID=1
* UPDATE #10 removes ID=4

However: when I run diff between the UPDATE #5 and UPDATE #8, the reinserted actions are not exactly the same. The differences are:

``` 	
--- pretty.5	2021-03-10 17:46:23.035238649 +0100
+++ pretty.8	2021-03-10 17:46:23.162238396 +0100
@@ -395,7 +395,7 @@
 				<![CDATA[1]]>
 			</ID>
 			<MESSAGE>
-				<![CDATA[Tue Mar  9 16:04:44 2021 : [one.vm.action] Error performing action "undeploy-hard": This action is not available for state UNDEPLOYED]]>
+				<![CDATA[Tue Mar  9 16:05:03 2021 : [one.vm.action] Error performing action "undeploy-hard": This action is not available for state UNDEPLOYED]]>
 			</MESSAGE>
 			<REPEAT>
 				<![CDATA[0]]>
@@ -421,7 +421,7 @@
 				<![CDATA[4]]>
 			</ID>
 			<MESSAGE>
-				<![CDATA[Tue Mar  9 16:04:44 2021 : [one.vm.disksnapshotrevert] Could not revert to disk snapshot for VM 4308, wrong state UNDEPLOYED.]]>
+				<![CDATA[Tue Mar  9 16:05:03 2021 : [one.vm.disksnapshotrevert] Could not revert to disk snapshot for VM 4308, wrong state UNDEPLOYED.]]>
 			</MESSAGE>
 			<REPEAT>
 				<![CDATA[0]]>

```

So it looks pretty clear now: the scheduler or whoever tried to run the actions 1 and 4, during which I ran `onevm delete-chart` removing the action 1 and then 4, and then the scheduler wanted to update the `<MESSAGE>` stating that both actions failed, and reinserted them inadvertedly back. This is what you get when you use a SQL database for storing XML blobs instead of structured data in tables and columns - the atomic updates are hard. Oh well.

So, Álex - to reproduce this you would probably need to have failing actions because of wrong VM state, which the scheduler would repeatedly try to execute. Then it will race against `onevm delete-chart`.

**Comment by Yenya** [comment] 2021-03-10 17:20
It _should_ be possible to acchieve atomic updates with test-and-set approach:

UPDATE ... SET body = $new_value WHERE id = ... AND body = $old_value

and when the number of updated rows is not 1, it is necessary to SELECT and retry.

I expect there can be many race conditions similar to this one in OpenNebula.

**Comment by al3xhh** [comment] 2021-03-11 10:24
Hello @Yenya,

Thank you very much for all the information you provided and all the tests you have performed. After reviewing this, we have found the explanation.

The problem is that when some scheduled action fails, the scheduler is going to retry it (as you have seen) and then is going to update the VM template with the result of the action. In the meanwhile, the VM template can be updated using other way, for example using the command `onevm delete-chart`, so when the scheduler tries to update the VM template, the content will be different.

It is a race condition between two different clients, rather than atomic update issue.

The solution will require some effort, we are thinking in some kind of versioning on the XML documents in the DB, to know if we can safely update the object or we should discard the update. As this solution needs to many changes, we can't do it for 6.0 version as we are in feature freeze, so we will do it for 6.2 version.

Best,
Álex.

**Comment by paczerny** [comment] 2021-05-25 20:21
Fix will be included in 6.2 release

**Comment by tinova** [comment] 2021-08-31 08:57
needs testing

**Comment by FrederickBor** [comment] 2021-09-01 09:07
@tinova PRs to be approved:
- [Code](https://github.com/OpenNebula/one-ee/pull/1390)
- [Tests](https://github.com/OpenNebula/development/pull/1622)

**Closed** 2021-09-01 15:33 UTC
Labels: Category: CLI, Community, Category: Sunstone, Type: Bug, Status: Accepted, Priority: Normal
