### ISSUE TITLE
Wrong ```DISK_SIZE``` calculation for VM disks

### ISSUE THREAD

**Issue by Franco-Sparrow** [OpenNebula/one#6308] opened 2023-09-01 20:35 UTC
##  Description
I have a cluster running on Ubuntu 22.04. Since OpenNebula EE 6.6.1 the cluster has been giving with wrong DISK_SIZE calculation and this impact on other actions like backups. The storage solution for this cluster is a Gluster Distributed-Disperse volume. The ```du``` command is not retreiving the right size of the qcow2 disks, not even from the external Gluster server. Due to this, Sunstone is showing wrong VMs used disk space.

![WhatsApp Image 2023-09-01 at 3 34 03 PM](https://github.com/OpenNebula/one/assets/56793015/b0bbd61a-31b2-43d0-90d6-58800b1bf187)

Even after upgrade to OpenNebula EE 6.6.3, and run ```onedb fsck``` the error remains there:

![WhatsApp Image 2023-09-01 at 2 47 06 PM](https://github.com/OpenNebula/one/assets/56793015/96d5b7f2-d324-40f1-9dc4-8b55a36e0446)

An example of wrong calculation of the space using `du` command:

![WhatsApp Image 2023-09-01 at 3 35 03 PM](https://github.com/OpenNebula/one/assets/56793015/54199d92-1f08-487e-90a8-8d4bed47ead3)

## To Reproduce

Deploy an OpenNebula cluster with dedicated storage using SDS Gluster Distributed-Disperse volume. Start creating VMs and adding data inside those VMs.

## Expected behavior

DISK_SIZE should be getting a logic value, not greater than the maximmun available space for the disk.

## Quick Fix

Edit OpenNebula drivers and change the ```du``` command, adding the option `--apparent-size`:

```bash
/var/lib/one/remotes/datastore/rsync/backup:172:    BKSIZE=`du -sm --apparent-size  #{remote_host_path}/backup/`
/var/lib/one/remotes/tm/shared/monitor:99:        DISK_SIZE="\$(du -mL --apparent-size "\${VMDIR}/\${DISK}" 2>/dev/null | awk '{print \$1}')"
/var/lib/one/remotes/tm/shared/monitor:110:                SNAP_SIZE="\$(du -mL --apparent-size "\${SNAP_DIR}/\${SNAP}" 2>/dev/null | awk '{print \$1}')"
/var/lib/one/remotes/tm/ssh/ssh_utils.sh:129:    du -s -BM --apparent-size $1 | cut -f1 -d'M'
/var/lib/one/remotes/tm/ssh/monitor_ds:35:        disk_size="$(du -mL --apparent-size "${vmdir}/${disk}" 2>/dev/null | awk '{print $1}')"
/var/lib/one/remotes/tm/ssh/monitor_ds:46:                snap_size="$(du -mL --apparent-size "${snap_dir}/${snap}" 2>/dev/null | awk '{print $1}')"
/var/lib/one/remotes/tm/qcow2/monitor:99:        DISK_SIZE="\$(du -mL --apparent-size "\${VMDIR}/\${DISK}" 2>/dev/null | awk '{print \$1}')"
/var/lib/one/remotes/tm/qcow2/monitor:110:                SNAP_SIZE="\$(du -mL --apparent-size "\${SNAP_DIR}/\${SNAP}" 2>/dev/null | awk '{print \$1}')"
/var/lib/one/remotes/im/qemu-probes.d/host/system/monitor_ds.rb:70:        o, _e, s = Open3.capture3("du -sh --apparent-size #{path}")
/var/lib/one/remotes/im/kvm-probes.d/host/system/monitor_ds.rb:70:        o, _e, s = Open3.capture3("du -sh --apparent-size #{path}")
```

After a monitoring cycle, the `DISK_SIZE` is now getting the right values:

![WhatsApp Image 2023-09-01 at 3 55 28 PM](https://github.com/OpenNebula/one/assets/56793015/3b77df48-f53b-4fb7-90ec-a103a179541f)

With the new option in `du` command, the used space is more realistic now:

![WhatsApp Image 2023-09-01 at 3 36 05 PM](https://github.com/OpenNebula/one/assets/56793015/687fd8fe-f5aa-4066-8810-7a546170dbb0)

The command ```du``` is not from OpenNebula, and this maybe is not an issue from the project, but as is affecting the cluster I posted the issue here and the solution that I used.

I have 2 OpenNebula clusters and this is only happening in one of them. Should we use this quick fix in presence of these kind of errors or this might affect how OpenNebula should works by default?

**Details**
 - Affected Component: [Storage]
 - Hypervisor: [KVM]
 - Version: [6.6.1, 6.6.2, 6.6.3]

**Additional context**

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by Franco-Sparrow** [comment] 2024-01-24 15:45
Hi team. Did we have any advance on this? Check this output:

![image](https://github.com/OpenNebula/one/assets/56793015/faa69c15-ae1b-4ed2-b9cc-8a2ba0f716cc)

The `virtual size` is `10 GiB` while the `disk size` is `7.77 TiB`. Anyway, adding option `--apparent-size` to the `du` command fix the problem. This could be a hint to solve issue maybe, as this option is not being used by `du` command executions by opennebula code:

![image](https://github.com/OpenNebula/one/assets/56793015/b4f89aa8-ea1c-4c1b-aa5b-10c1344fb882)

**Comment by xorel** [comment] 2024-01-26 11:16
I don't think we can check the files with `--apparent-size` because usually the situation is exactly the opposite.

```
$ du -h /var/lib/one/datastores/0/247797/disk.0.snap/0                          
2.7G    /var/lib/one/datastores/0/247797/disk.0.snap/0

$ du -h /var/lib/one/datastores/0/247797/disk.0.snap/0 --apparent-size
3.6G    /var/lib/one/datastores/0/247797/disk.0.snap/0
```

qcow2 images containing holes use less real disk space then what `--apparent-size` says. 

I don't understand how du/qemu can reports 7.8T in your case 🤔

**Comment by Franco-Sparrow** [comment] 2024-01-26 11:53
Hi @xorel

I will rebuild the cluster in the following days, changing the storage backend from external to hyper-converged. I will migrate these images to new cluster with the hope to get the right disk size. Is isane how `qemu` thinks that the disk has 7.8T, while I dont have that storage available and make the FS able to copy this image with less storage. Some how, `du` command is also getting confused with the size.

Will update soon!!!

**Comment by xorel** [comment] 2024-02-14 14:44
I am closing the issue as "can not reproduce", please re-open it when you have some update.

**Closed by xorel** 2024-02-14 14:44 UTC
Labels: Status: Pending, Category: Drivers - Storage, Type: Bug
