### ISSUE TITLE
vms remain in state "UNKNOWN" after loss of connection

### ISSUE THREAD

**Issue by philfry** [OpenNebula/one#5121] opened 2020-10-07 11:57 UTC
**Description**
In my setup the controller is in another data center as some of the satellites. Sometimes the connection between the controller and the satellites might fail because of network problems.

Then the vm's status is updated to "UNKNOWN" (```New LCM state is UNKNOWN```) and the satellites (hosts) are marked as offline/error.

Once the network connections have recovered the satellites (hosts) are shown as "on" but the vms are not changing their state.

The monitoring messages are still being sent from the satellite to the controller (4124/udp) (the traffic arrives at the controller, too):
```
BEACON_HOST SUCCESS 2 1602071187 [somebase64string]
MONITOR_HOST SUCCESS 2 1602071254 [somebase64string]
VMONITOR_VM SUCCESS 2 1602071257 [somebase64string]
… and so on
```
Restarting opennebula (which restarts onemonitord) didn't help. The vm's status is not updated until I force a stats update: ```onehost forceupdate -c myclusterid```.

**To Reproduce**
- block the network connections between controller and satellites
- wait until the hosts are in error state and the vm state is "unknown"
- unblock the network connections
- wait

**Expected behavior**
The vms should be shown as "running" (or whatever the real state is) as soon as the satellites/hosts are reachable again

**Details**
 - Affected Component: monitord
 - Hypervisor: kvm
 - Version: 5.12.0.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by Githopp192** [comment] 2021-01-15 19:23
Thx Philippe - happened to me, too - today.
(being on "ON 5.12.0.1").
i've got duplicate IP - unfortunately the origin IP was Sunstone - so my IP-Switch went down and i had to restart sunstone server.
After that some of my VM's got the State "**unkn**".

After putting your command the VMs recovered with the correct state (i had also a wild vm with wrong state "running", but was indeed down - after putting the "forceupdate" also this VM did show the correct state (poff)).

**Comment by majidrajabi** [comment] 2021-11-06 19:12
Same problem for disconnecting some hosts for a while. Opennebula 5.11.90

**Comment by al3xhh** [comment] 2022-06-08 14:43
Tested on 6.4 version and can't reproduce the issue:

```
Wed Jun  8 16:32:53 2022 [Z0][VM][I]: New LCM state is UNKNOWN                  
Wed Jun  8 16:33:40 2022 [Z0][LCM][I]: VM found again by the drivers            
Wed Jun  8 16:33:40 2022 [Z0][VM][I]: New LCM state is RUNNING 
```

Closing it, open if needed.

**Closed by al3xhh** 2022-06-08 14:43 UTC
Labels: Community, Category: Drivers - Monitor

**Comment by xHybriddd** [comment] 2025-06-24 08:53
Same problem on version 6.10.0. The already mentioned command`onehost forceupdate -c myclusterid` solved the status problem.
