### ISSUE TITLE
VNC "address already in use"

### ISSUE THREAD

**Issue by GermanG** [OpenNebula/one#2721] opened 2018-12-13 08:33 UTC
**Description**
When creating a VM with high ID number, the VNC port assignment may conflict with an already running process owned TCP port (as client) and unable to start qemu-kvm process because of it. 

**To Reproduce**
This is difficult to reproduce because the opennebula generated VNC port must conflict with an already running process in the host server.

**Expected behavior**
There isn't just one, I have this ideas:
1. Let libvirt figure out the VNC port and update VM port accordingly (I think this might have problems with SunStone's VNC proxy, I need to check your implementation, becuase the port numbers will repeat).
1. Recalculate the port so there's one free that host and update VM port accordingly.
1. Undeploy and reschedule on failure (maybe configurable N retries before give up)

**Details**
 - Affected Component: oned + kvm driver.
 - Hypervisor: KVM
 - Version: 5.4.15 

**Additional context**
Because of our volume, this is happening more than once a week.
Today we are solving that manually and when a VM is reported by the user we just reschedule it and gets assigned to another host, chance are this won't happen again.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by GermanG** [comment] 2018-12-13 08:37
This was already reported [here](https://dev.opennebula.org/issues/3885) but marked as duplicate, I think the user also run into the same issue. Although the probability is low, when you reach a volume even .5% translates into affected users.

**Comment by jramosf** [comment] 2018-12-13 08:58
My vote would be for just using one free port for VNC

**Comment by christian7007** [comment] 2018-12-17 16:32
Duplicate of #1227

**Closed by christian7007** 2018-12-17 16:32 UTC
