### ISSUE TITLE
storage/marketplace in sunstone broken when a custom(and misconfigured) http marketplace is added

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#5348] opened 2021-04-16 08:01 UTC
**Description**
When a http marketplace is added, but with invalid BASE_URL the Storage/MarketPlaces tab is broken only an error message is raised: _It appears there was a server exception. Please check server's log_.

**To Reproduce**
Create a HTTP marketplace with BASE_URL that returns 404
Check Storage/MarketPlaces
The page is blank with the above exception

**Expected behavior**
The page should show the configured marketplaces and mark somehow the state of the "broken" marketplace only

**Details**
 - Affected Component: [Sunstone]
 - Hypervisor: [KVM]
 - Version: [6.0.0]

**Additional context**
_onemarket show_ do not have this issue and shows all marketplaces

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment] 2021-12-15 13:44
We will close this issue because we can't reproduce it in version 6.2.
If you can reproduce it in that version, feel free to reopen it.

**Closed by FrederickBor** 2021-12-15 13:44 UTC
Labels: Community, Category: Sunstone, Status: Accepted, Priority: Normal
