### ISSUE TITLE
nic pci passthrough in ONe 5.12 no longer works

### ISSUE THREAD

**Issue by philfry** [OpenNebula/one#5125] opened 2020-10-12 08:11 UTC
**Description**
The resulting vm definition that is passed to virsh in 5.12 no longer declares a pci passthough nic as `hostdev` but as a bridge. The vm cannot start because the dummy "bridge" is not found virsh. Even if it started the nic would not be a pci passthrough device.

**To Reproduce**

_network definition (name: sriov-vf-network)_
```xml
<TEMPLATE>
  <BRIDGE><![CDATA[sriov]]></BRIDGE>
  <BRIDGE_TYPE><![CDATA[linux]]></BRIDGE_TYPE>
  <DESCRIPTION><![CDATA[sriov virtual function]]></DESCRIPTION>
  <LABELS><![CDATA[mylabel]]></LABELS>
  <OUTER_VLAN_ID><![CDATA[]]></OUTER_VLAN_ID>
  <PHYDEV><![CDATA[]]></PHYDEV>
  <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
  <VLAN_ID><![CDATA[]]></VLAN_ID>
  <VN_MAD><![CDATA[dummy]]></VN_MAD>
</TEMPLATE>
```

_vm definition_
```xml
<TEMPLATE>
  <PCI>
    <CLASS><![CDATA[0200]]></CLASS>
    <DEVICE><![CDATA[8090]]></DEVICE>
    <NETWORK><![CDATA[sriov-vf-network]]></NETWORK>
    <NETWORK_UNAME><![CDATA[oneadmin]]></NETWORK_UNAME>
    <SECURITY_GROUPS><![CDATA[0]]></SECURITY_GROUPS>
    <TYPE><![CDATA[NIC]]></TYPE>
    <VENDOR><![CDATA[1077]]></VENDOR>
  </PCI>
</TEMPLATE>
```
_resulting deployment.0_
```xml
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <devices>
    <interface type='bridge'>
      <source bridge='sriov'/>
      <mac address='aa:05:ca:ba:98:00'/>
      <target dev='one-65-1'/>
      <model type='virtio'/>
    </interface>
  </devices>
</domain>
```

**Expected behavior**

_resulting deployment.0_
```xml
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <devices>
    <hostdev mode='subsystem' type='pci' managed='yes'>
      <source>
        <address  domain='0x0000' bus='0x43' slot='0x14' function='0x0'/>
      </source>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x01' function='0'/>
    </hostdev>
  </devices>
</domain>
```

**Details**
 - Affected Component: 
 - Hypervisor: kvm
 - Version: 5.12.0.1

**Additional context**
This config worked fine with OpenNebula 5.10.5

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by rsmontero** [comment] 2020-11-11 09:18
It seems we cannot reproduce this issue, see:

https://forum.opennebula.io/t/nic-pci-passthrough-acts-differently-on-one-5-12/8875/2

Closing for now

**Closed by rsmontero** 2020-11-11 09:18 UTC
