### ISSUE TITLE
Virtual Network Template CLUSTER_IDS attribute is not correctly set

### ISSUE THREAD

**Issue by christian7007** [OpenNebula/one#5423] opened 2021-06-15 14:49 UTC
**Description**
From the documentation:

"When a network is created by instantiating a Virtual Network Template, it is associated to the default cluster. You can control which clusters the networks will be in with the `CLUSTER_IDS` attribute."

Instead of setting the `CLUSTER_IDS` attribute, Sunstone is setting the `CLUSTER` attribute, so the resulting networks are assigned to the default cluster (0).

**Expected behavior**
`CLUSTER_IDS` attribute is set instead of `CLUSTERS`

**Details**
 - Affected Component: Sunstone
 - Version: 6.0

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by FrederickBor** [comment] 2021-06-22 13:48
Closing this since we can't reproduce it

**Closed by FrederickBor** 2021-06-22 13:48 UTC
Labels: Category: Sunstone, Priority: Normal, Type: Bug
