### ISSUE TITLE
Error getting host after upgrade to 5.10.1

### ISSUE THREAD

**Issue by josephmilla** [OpenNebula/one#4099] opened 2020-01-14 21:45 UTC
**Description**
In OpenNebula 5.10.1, the sunstone Hosts section (Sidebar > Infrastructure > Hosts > Select a host) lost access to vital host information. The error seems to be a 404 on the /host endpoint `/host/X?id=Y&csrftoken=ZZZ`

**To Reproduce**
Upgrade OpenNebula 5.8.5 to 5.10.1 and go through the following: Sidebar > Infrastructure > Hosts > Select a host

![Imgur](https://imgur.com/8e7ZIVs.png)

![Imgur](https://imgur.com/r3BnwUh.png)

**Expected behavior**
The expected behavior is for it have information about the hosts.

**Details**
 - Affected Component: Sunstone
 - Hypervisor: N/A
 - Version: 5.10.1

**Additional context**

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by josephmilla** [comment] 2020-01-14 23:03
It seems like it's not only isolated to sunstone. Anything related to a host (even deployment of new VM's) are failing:
```
Error deploying virtual machine 1298 to HID: 1. Reason: [one.vm.deploy] Error getting host [1].
```

**Comment by dann1** [comment] 2020-01-14 23:54
Could you open an entry in the forum to discuss this? It's a better place to deal with non bug/features issues (maybe there was an error upgrading) and you are more exposed to the community help. Check `/var/log/one/oned.log` to look for clues about this error.

**Comment by josephmilla** [comment] 2020-01-15 00:47
I ended up reverting back to 5.8.5, I'll just wait till there's a more stable release of 5.10.x.

This was from `/var/log/one/oned.log`. 
```
Error deploying virtual machine 1298 to HID: 1. Reason: [one.vm.deploy] Error getting host [1].
```

No obvious error from the logs nor strace.

**Comment by rsmontero** [comment] 2020-01-15 10:42
@joseangelgm This error is most likely to be a DB corruption during the upgrade. WE can take a look if you send us the output of the following command:

```
$ (export EDITOR=`which cat` ;onedb update-body -u <db_user> -p <db_password> -d <db_name> host --id 0)
```

**Comment by Compunctus** [comment] 2020-01-22 13:31
Had the same problem. Had to manually (onedb update-body on leader node) add following attributes:
<PREV_STATE>
    <VMS_THREAD>1</VMS_THREAD>
    <NUMA_NODES>

**Comment by christian7007** [comment] 2020-01-22 15:24
Hello guys, can you confirm that you did run `onedb upgrade` command after updating the packages?

The `PREV_STATE` attribute is created during the db upgrade process, check: https://github.com/OpenNebula/one/blob/530d962b292a274d122c7e6815fb1b52ee131faf/src/onedb/local/5.8.0_to_5.10.0.rb#L85

I've been making some tests locally and it seems to works for me.

**Comment by Compunctus** [comment] 2020-01-22 15:29
I did, but for some reason i had local table version 5.6.0 before upgrading. I distinctly remember running onedb upgrade while doing 5.6.0 -> 5.8.1...

My update history:
Version:   5.4.1
Timestamp: 10/05 19:05:50
Comment:   OpenNebula 5.4.1 daemon bootstrap

Version:   5.6.0
Timestamp: 08/03 17:22:09
Comment:   Database migrated from 5.4.1 to 5.6.0 (OpenNebula 5.6.0) by onedb command.

Version:   5.10.0
Timestamp: 01/22 13:39:14
Comment:   Database migrated from 5.6.0 to 5.10.0 (OpenNebula 5.9.80) by onedb command.

**Comment by christian7007** [comment] 2020-01-22 15:43
If would be useful if you can share a backup of your database previous to the update so we can try to reproduce the error, it would be enough with the `host_pool` table.

Also did you remember any error during the DB upgrade process?

NOTE: regarding the `5.6.0` issue probably you are looking at shared table, which wasn't incremented to `5.8.0` as no shared table was modified in `5.8.0`. Try `select * from local_db_versioning`

**Comment by Compunctus** [comment] 2020-01-22 15:53
yeah, i was looking at shared table; local db versioning attached.
also attached host_pool dump.
[localversioning.txt](https://github.com/OpenNebula/one/files/4098176/localversioning.txt)
[host_pool_5.8.0.txt](https://github.com/OpenNebula/one/files/4098178/host_pool_5.8.0.txt)

**Comment by christian7007** [comment] 2020-01-22 17:27
I've upgrade a DB with your `host_pool` table dump and it did works fine for me. Maybe you missed some error during the DB upgrade process.

@josephmilla it would be useful if you double check that when trying to update again and tell us if any error appears.

**Comment by josephmilla** [comment] 2020-01-23 01:41
> yeah, i was looking at shared table; local db versioning attached.
> No, i don't think that there were any upgrade errors on 5.6.0 -> 5.8.0 and 5.8.0 -> 5.10.0; upgrade and fsck went fine (apart from one vm record not being closed, but that should not affect anything)
> also attached host_pool dump.
> [localversioning.txt](https://github.com/OpenNebula/one/files/4098176/localversioning.txt)
> [host_pool_5.8.0.txt](https://github.com/OpenNebula/one/files/4098178/host_pool_5.8.0.txt)

@christian7007 I basically did what @Compunctus went through; also did upgrades and fsck on the db. I can try to upgrade to 5.10.1 again when I get the chance. As of now, I've downgraded to back to 5.8.5.

**Comment by christian7007** [comment] 2020-01-23 12:29
Yes @josephmilla , it would be nice if you can update the issue with any error you can see during the upgrade process so we can figured it out why the DB upgrade process is failing for both of you.

**Comment by christian7007** [comment] 2020-01-31 11:33
Hello @josephmilla and @Compunctus, could you share which OS and Ruby version are you using. We keep working on reproduce the issue but we are not able to do it.

**Comment by Compunctus** [comment] 2020-02-03 13:39
Neither am i, production upgraded successfully.
Both dev and prod use fully updated CentOS7 without additional ruby repos/packages.
CentOS: CentOS Linux release 7.7.1908 (Core)
Ruby: 2.0.0.648-36.el7

**Comment by sulaweyo** [comment] 2020-02-22 08:09
I just ran into that issue as well upgrading from 5.4.15 to 5.10.2 
I added the PREV_STATE and the nodes were fine again. onedb fsck did not see the issue nor did the upgrade call add it. 

As i'm running on Arch and this is unsupported i only wanted to say that it happened there. 
Ruby 2.7.0p0

**Comment by rsmontero** [comment] 2020-03-26 17:24
We will add some notes in known issues as it is difficult to reproduce.

**Comment by christian7007** [comment] 2020-03-27 09:19
We are closing this ticket as we are not able to reproduce it. Please reopen if any new information about it is found.

**Closed by christian7007** 2020-03-27 09:19 UTC
Labels: Category: Core & System, Community, Priority: Normal, Status: Pending, Type: Bug
