### ISSUE TITLE
Can't attach disk after detaching disk

### ISSUE THREAD

**Issue by atodorov-storpool** [OpenNebula/one#1703] opened 2018-01-31 15:28 UTC
# Bug Report
## Version of OpenNebula

- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [ ] 5.4.4
- [ ] 5.4.5
- [X] 5.4.6
- [X] Development build

## Component

- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] Federation and HA
- [ ] Host, Clusters and Monitorization
- [X] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [ ] Packages
- [ ] Scheduler
- [ ] Storage & Images
- [ ] Sunstone
- [ ] Upgrades
- [ ] User, Groups, VDCs and ACL
- [ ] vCenter

## Description

Disk attach failed with following error:
```
Could not open '/var/lib/one/datastores/109/95/disk.2': Operation not permitted
```
### Expected Behavior
Disk attached

### Actual Behavior
Disk not attached

## How to reproduce

Detected on CentOS 7.4 with qemu-kvm-ev (latest updates)
Upstream issue: https://bugzilla.redhat.com/show_bug.cgi?id=1469235
Further info: https://www.redhat.com/archives/libvir-list/2017-January/msg00790.html

Proposed resolution is to disable the namespaces writing "namespaces = [ ]" in /etc/libvirt/qemu.conf

**Comment by vholer** [comment] 2018-05-04 09:39
Hi @atodorov-storpool,

is this still valid bug for you with the latest libvirt/QEMU-EV packages? I'm not able to reproduce with:

```
qemu-kvm-ev-2.9.0-16.el7_4.14.1.x86_64
libvirt-3.2.0-14.el7_4.9.x86_64
```

If yes, can you please provide steps to reproduce? Thank you very much!

**Comment by atodorov-storpool** [comment] 2018-05-04 14:49
Hi @vholer,

On a HV with older versions  `qemu-img-ev-2.9.0-16.el7_4.13.1.x86_64` and `libvirt-3.2.0-14.el7_4.7.x86_64` it is reproducible. To reproduce you must drive ONE to change the symlink `disk.X -> dev A` to `disk.X -> dev B`. For example:

1. Create three persistent images - A, B and C.
2. Attach them in order A, B, C, (you have disk.2->A, disk.3->B, disk.4->C)
3. Detach C (disk.4 symlink is removed)
4. Detach B (disk.3 symlink is removed)
5. Attach C (disk.3->C)

You should receive the following error:

```
Fri May  4 16:58:25 2018 [Z0][VMM][E]: attach_disk: Command "virsh --connect qemu+tcp://localhost/system attach-device one-185 /var/lib/one//datastores/103/185/disk.3.attach" failed: error: Failed to attach device from /var/lib/one//datastores/103/185/disk.3.attach
Fri May  4 16:58:25 2018 [Z0][VMM][I]: error: internal error: unable to execute QEMU command '__com.redhat_drive_add': Device 'drive-scsi0-0-0-0' could not be initialized
```
and in `/var/log/libvirt/qemu/one-185.log`:
```
Could not open '/var/lib/one//datastores/103/185/disk.3': Operation not permitted
```
Looks line it is fixed in latest `EV` versions that you quote.

But not sure for the other distros though.

**Comment by vholer** [comment] 2019-03-06 11:57
As this was a problem with particular (old) QEMU release(s) and fixed in later versions, I'm going to close the issue.

**Closed by vholer** 2019-03-06 11:57 UTC
Labels: Category: Documentation, Category: Packages, Community, Status: Pending, Type: Bug
