### ISSUE TITLE
Cannot update template. Tried to change restricted attribute: USER_INPUTS

### ISSUE THREAD

**Issue by myjapan** [OpenNebula/one#5153] opened 2020-10-29 16:50 UTC
**Description**
I get the error “[one.template.update] Cannot update template. Tried to change restricted attribute: USER_INPUTS” when a group admin tries to modify the context of a template with fixed Memory, Cpu or vCpu parameters

**To Reproduce**
1- As admin, create a template with fixed memory, cpu and vcpu parameters
2- Set the proper permission to customers
3- As simple user in the groupadmin view, try to alter any voice in the context tab (example, add a ssh key)
4- I get the error in subject

**Expected behavior**
The template is modified with no errors, and the constraints on memory and cpu are maintained

**Details**
 - Affected Component: Suntone, Wizard mode
 - Hypervisor: KVM
 - Version: 5.12.0.3

**Additional context**
As workaround, I tried to comment out the USER_INPUTS lines in etc/one/oned.conf
Then, when the customer tries to upload the ssh key, the template gets modified and the memory, cpu and vcpu constraints are removed from the template
![immagine](https://user-images.githubusercontent.com/10814527/97605172-9e24ac80-1a0e-11eb-9b2d-58ae8b188829.png)

So, I removed the comments from the USER_INPUTS lines and tried to edit the template file in Sunstone using "advanced" tab.
Things goes better: I can edit or add/delete the ssh key, so the problem could be related only to the Wizard in Sunstone?

Thanks 
Marco

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by sbbarragan** [comment] 2021-01-05 15:42
cannot reproduce this, closing until more feedback is provided.

**Closed by sbbarragan** 2021-01-05 15:42 UTC
Labels: Category: Sunstone
