### ISSUE TITLE
VM snapshot lost after migration

### ISSUE THREAD

**Issue by rene-bayer** [OpenNebula/one#5530] opened 2021-09-02 10:03 UTC
**Description**
a vm snapshot (not disk snapshot) is broken/lost after live migration or power-off

**To Reproduce**

- create  a new virtual machine named test1 and start it
- open the virtual machine in sunstone, navigate to "Snapshots" and create one
- wait for the snapshot to finish
- live migrate vm "test1" to an other hypervisor
- the snapshot is still listed in sunstone, but with `virsh snapshot-list <domain>` we see that the snapshot is gone
- there's no way to remove that broken snapshot in sunstone anymore

- create a new virtual machine named test2 and start it
- open the virtual machine in sunstone, navigate to "Snapshots" and create one
- wait for the snapshot to finish
- power off vm "test2"
- snapshot in sunstone is gone
- power on vm "test2"
- snapshot in sunstone is still gone, but with `virsh snapshot-list <domain>` you can still see the snapshot

**Expected behavior**
In both cases I would expect the snapshot to be still there and correctly shown in Sunstone

**Details**
 - Affected Component: Sunstone, Storage, libvirtd
 - Hypervisor: KVM
 - Storage: shared fs - TM_MAD="qcow2"
 - Version: 6.0.2

**Additional context**
NaN

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by atodorov-storpool** [comment] 2021-09-02 10:35
duplicate of https://github.com/OpenNebula/one/issues/5444

**Comment by atodorov-storpool** [comment] 2021-09-02 10:37
The snapshots created by opennebula are of type internal and they are discarded on domain poweroff and migrate

**Comment by DarkSunOne** [comment] 2021-09-02 10:43
Okay, but even then, the current behavior is wrong...
So the expected behavior should be that the snapshot is cleared everywhere in every situation, on opennebula side and libviert side.

**Comment by christian7007** [comment] 2021-09-02 12:10
Hi @DarkSunOne,

Regarding the problem when the VM is powered off. Can you confirm that you have the `KEEP_SNAPSHOTS = "yes"` in the KVM `VM_MAD` section of your oned.conf. If not, could you set it and try that case again?

**Comment by DarkSunOne** [comment] 2021-09-09 05:36
Hi @christian7007 
sry took a little ...

With the change `KEEP_SNAPSHOTS = "yes"` the snapshot is not removed when powering off the VM.


This generally changes the behavior a little...

Now, when I live migrate the VM, the snapshot is still gone, but if I poweroff and start the VM again, the snapshot is redefined correctly


As far I can see ... you're removing the snapshots before migration [here](https://github.com/OpenNebula/one/blob/eb49ad2e6f8a90c1247cf34eda09a1ad89bc63ce/src/vmm_mad/remotes/kvm/migrate#L105) but dont redefine it again after the successful migration.

While during power on this is done correctly ... see [here](https://github.com/OpenNebula/one/blob/eb49ad2e6f8a90c1247cf34eda09a1ad89bc63ce/src/vmm_mad/remotes/kvm/deploy#L41)

**Comment by christian7007** [comment] 2021-09-09 07:15
Hi @DarkSunOne,

Yes, currently that's the expected behavior.

**Comment by DarkSunOne** [comment] 2021-09-09 07:18
Can't believe that cause the handling with the snapshot is still buggy.

When you live migrate a VM with a snapshot (as a hosting provider for example during the updates), you cant revert or delete the snapshot within the Sunstone, cause the snapshot isn't defined anymore on libvirt side.

**Comment by christian7007** [comment] 2021-09-09 16:01
Actually, that feature was never supported. Libvirt will fail if trying to migrate a VM with snapshots, so they needs to be removed, which is a different issue than the poweroff.

We've already scheduled this issue for 6.2.1 and we'll look on what's the best way of recreating the snapshots after the live migration.

**Comment by rsmontero** [comment] 2022-01-14 15:26
Merged

**Closed by rsmontero** 2022-01-14 15:26 UTC
Labels: Status: Pending, Category: KVM, Type: Bug, Sponsored, Priority: Normal
