### ISSUE TITLE
Add Disk Snapshots to scheduled VM actions

### ISSUE THREAD

**Issue by lbtq** [OpenNebula/one#2340] opened 2018-08-02 19:09 UTC
**Description**
Currently the Scheduled VM Actions in Sunstone allow for scheduling VM snapshots (disk + memory).  Unfortunately VM snapshots are not supported for RAW or Ceph RBD backed disks, so disk snapshots have to be used.  Disk snapshots are not currently available as a Scheduled VM Action, so support needs to be added.  This is an extremely common feature with most "cloud" offerings, so would help to bring OpenNebula to feature parity with other platforms, and be much more user friendly to end users on RAW or RBD backed deployments.

**Use case**
This feature will optimally allow users to set up recurring scheduled disk snapshots via the VM Actions tab in the Sunstone UI.  Support for cleaning up old snapshots would also be useful.

**Interface Changes**
Add a "disk-snapshot-create" option under the "Add Action->New scheduled action" heading on the VM Actions tab in Sunstone.  Possibly allow for specifying which disk to snapshot if multiple disks are attached (default to the first/OS disk).

**Additional Context**
There are already several issues (1300, 1829, 1548) requesting this feature that have been closed.  It looks like it may have slipped through the cracks for 5.6.

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by OpenNebulaSupport** [comment] 2019-03-19 11:13
Also add the ability to:

  - schedule delete system and disk snapshots

**Comment by treywelsh** [comment] 2020-06-15 12:47
Hi :)

Nice to see disk actions added !
I have a small questions on the intended behavior in case of a scheduled disk action:

Consider a scheduled disk action, if the disk is detached, will the related scheduled actions be removed at the same time ?

**Comment by al3xhh** [comment] 2020-06-15 13:40
Hello @treywelsh 

Nice to hear that you like the new functionality!

> Consider a scheduled disk action, if the disk is detached, will the related scheduled actions be removed at the same time ?

If you remove the disk, the schedule action will remain on the Virtual Machine and it is going to fail, as OpenNebula is not able to find the disk to snapshot it.

Best,
Álex.

**Comment by al3xhh** [comment] 2020-06-15 13:42
Closing it as the functionality is already implemented and merged.

**Closed by al3xhh** 2020-06-15 13:42 UTC
Labels: Category: Core & System, Category: Scheduler, Priority: Normal, Type: Feature

**Comment by treywelsh** [comment] 2020-06-15 14:17
Thank you for your quick response.

The starting point that lead me to the question above was:

The disk ID is unique only at a given point in time, so, if the last disk of a VM is detached, and just after, an other disk is attached, the same ID will be used, so the same scheduled action will continue on the new disk. I may not want this behavior.
(Same consideration for snapshot ID if I create/delete snapshot, ID number are reused, so I could delete the wrong snapshot later)

I'm trying to find a way to detect this kind of cases with ID reuse, at least to fire a warning that something potentially unexpected happened.

For now as I understand, at best, I can only use some complex hooks (on one.vm.disksnapshotcreate API call etc.) to improve this.

Other ways would require feature request like custom action scheduling, or add a disk number notion (and avoid disk ID reuse in increasing the ID like VM and image IDs...).
